### ISSUE TITLE
[feature request] feeding reminder with calander data (Amazfit GTS) 

### ISSUE THREAD

**Issue by AlphaX2** [piggz/harbour-amazfish#101]
Hi there,

a (more or less) simple feature request: 
it seems to be useful and handy to fill the Amazfit (GTS) reminders section with calendar entries. It should be made optional from Amazfish settings, because I believe not everyone wants this as default. This option could replace the "Timeline" feature, that I was used to from my Pebble.

Thanks.

**Comment by piggz** [comment]
Should be possible, tho i dont think this is currently implemented by gadget bridge so would have to be reverse engineered.  Would you be willing to supply bluetooth hci snoop logs showing the data transfer for these events from an android device?

**Comment by AlphaX2** [comment]
I could possibly do some "research", but I just have a non-rooted Android device and need some help for sure. :)

**Comment by piggz** [comment]
It ok, ive got the logs myself and am decoding it

**Comment by piggz** [comment]
This is now in the repository
