### ISSUE TITLE
My Mi Band 2 has Bluetooth name MI Band 2

### ISSUE THREAD

**Issue by cy8aer** [piggz/harbour-amazfish#102]
I tried to couple my Mi Band 2 but it failed. Then I found out that the device shows up in bluetooth settings as "MI Band 2" with an upper case I.
This fixes it for me:
```
diff --git a/ui/qml/pages/PairSelectDeviceType.qml b/ui/qml/pages/PairSelectDeviceType.qml
index f9dbecd..bc5d868 100644
--- a/ui/qml/pages/PairSelectDeviceType.qml
+++ b/ui/qml/pages/PairSelectDeviceType.qml
@@ -68,7 +68,7 @@ Page {
                 icn: "../pics/devices/miband2.png"
 
                 onClicked: {
-                    pushPairPage("Mi Band 2", false);
+                    pushPairPage("MI Band 2", false);
                 }
             }
```

But if there are other people outside where the paring actual works there may be two different bluetooth names in the wild.

**Comment by piggz** [comment]
Ah, ok, i changed that to be in line with the band 3, which uses a lower case i, ill change it back if the band 2 uses something different!

**Comment by piggz** [comment]
This is fixed and will be in the next release
