### ISSUE TITLE
Build error: 

### ISSUE THREAD

**Issue by Thaodan** [piggz/harbour-amazfish#11]
I tried to build your sources but get this error during building(on your current master):
```
´/home/bidar/dev/sailfish/git/harbour-amazfish/qble/qbledevice.h:-1: In constructor **'BipDevice::BipDevice()':**
/home/bidar/dev/sailfish/git/harbour-amazfish/qble/qbledevice.h:27: Fehler: 'void QBLEDevice::propertiesChanged(const QString&, const QVariantMap&, const QStringList&)' is protected
     Q_SIGNAL void propertiesChanged(const QString &interface, const QVariantMap &map, const QStringList &list);
                  `
```

**Comment by piggz** [comment]
check the updated qble repo, ive now pushed that change....im working on it all atm tho so its untested!

**Comment by Thaodan** [comment]
thanks
One suggestion: push your current work to a different branch pefore pushing.
With this development is more open and users can react to your changes or test them without breaking anything (like chaging the pairing backend for example).

**Comment by piggz** [comment]
Normally, on larger projects, i would work on a feature branch, go through a review and do a squash onto master, but it didnt seem worth it for a one man little app like this in the very early stages of development.  It will certainly make sense going forward as it grows though, and i'll try and keep it in mind.
