### ISSUE TITLE
Ubports support?

### ISSUE THREAD

**Issue by Qiangong2** [piggz/harbour-amazfish#119]
Is there any chance to get this working on ubports? Since the pinephone is launching with ubports as its main OS, this would be a great and helpful addition

**Comment by piggz** [comment]
Its certainly possible.  The code is split between a daemon that should build with fairly minimal dependencies, and a UI that is sailfish specific.  The UI part would need redone for UB Touch, but its all QML talking over dbus, so not too difficult.

**Comment by Qiangong2** [comment]
That's awesome :)

Maybe I'll consider replacing my fitbit with an amazfit then instead of an asteroid os watch

**Comment by jmlich** [comment]
I will be happy for feedback on pull request
https://github.com/piggz/harbour-amazfish/pull/265

**Comment by jmlich** [comment]
@piggz I guess, this can be closed
