### ISSUE TITLE
Split background functionality from app

### ISSUE THREAD

**Issue by Thaodan** [piggz/harbour-amazfish#12]
I was thinking about making something like an dbus service that is activated on request when the app is paired and thus removing the need of having the app open.
I'll try to help on this however my c++ skills are limited.

**Comment by piggz** [comment]
It is already on my plan to do this.  If you see in the code, there is little communication between the QML gui and the backed, eg, all the settings are set to dconf, then the backend is told to update.  This was to allow me to convert the backend code to a daemon in the future, after its stabilised.

I also want to create a generic dbus service for heartrate data, so the likes of laufhelden can read without needing to know the watch protocol.

**Comment by piggz** [comment]
Done
