### ISSUE TITLE
Question: amazfit GTR support

### ISSUE THREAD

**Issue by armorica** [piggz/harbour-amazfish#123]
On openrepos you mention GTR support in your development code. As I'm considering a new watch and the GTR appeals me most, having an app on Sailfish, I'm wondering when do you expect it to become available?

As the latest openrepos release was done on june 16th, it appears that the repo here at github is running behind?

Regards,

Paul Tap

**Comment by piggz** [comment]
GTR support is pushed and in 1.6.0
