### ISSUE TITLE
Data base issue with GTS 0.0.9.12 and Amazfish 1.6.5-1 with update for 1.6.6-1

### ISSUE THREAD

**Issue by mklick** [piggz/harbour-amazfish#126]
Update for 1.6.6.-1 installed 2020-07-18
Weather seems to work now. The is still a data consistency issue, please find latest screenshots of watch and Amazfish fro comparison (same time). In particular the steps makes no sense.
Please let me know if you need more or other data.

![IMG_20200718_094919_edit](https://user-images.githubusercontent.com/67764210/87848446-dcbfac80-c8e0-11ea-8937-02a5b40d852e.jpg)
![Screenshot-20-07-18-10-06-22](https://user-images.githubusercontent.com/67764210/87848447-e34e2400-c8e0-11ea-9d15-0275a5d4698a.png)

Hi piggz. Connect works now and the real-time data are correct. But there are now incorrect data in the data base, also already from the future. Maybe the date format for downloading blocks of data was also changed. Please check the screenshots attached. Weather, working before the firmware update properly, does not work, too.

![Screenshot-20-07-09-14-13-44](https://user-images.githubusercontent.com/67764210/87040046-63dd9800-c1f0-11ea-8850-749e2915adf6.png)
![Screenshot-20-07-09-14-13-36](https://user-images.githubusercontent.com/67764210/87040052-65a75b80-c1f0-11ea-8bb3-26c91b90879b.png)
![Screenshot-20-07-09-14-13-29](https://user-images.githubusercontent.com/67764210/87040058-68a24c00-c1f0-11ea-9564-0e9f65be6ff7.png)
![Screenshot-20-07-09-14-13-18](https://user-images.githubusercontent.com/67764210/87040064-6a6c0f80-c1f0-11ea-9268-1bbe8dac9d23.png)
![Screenshot-20-07-09-14-13-09](https://user-images.githubusercontent.com/67764210/87040067-6cce6980-c1f0-11ea-8f5f-e5245d01a60d.png)

**Comment by piggz** [comment]
Can you check if this is still an issue?
