### ISSUE TITLE
Umlauts are displayed as [?] (UTF)

### ISSUE THREAD

**Issue by Thaodan** [piggz/harbour-amazfish#13]
I noticed Umlauts (and maybe other special characters) are displayed as ?.

**Comment by je-nix** [comment]
Sorry for the late reply, I just got my Amazfit this week.
You can solve this by installing a font with UTF-8 support. I took mine from https://forum.xda-developers.com/smartwatch/amazfit/amazfit-bip-cor-eu-support-font-pack-t3872210
Just grab the "Mili_chaohu_uni_v17.zip" attachment (or a newer version, if one is available), extract it and send the font file to the Bip via the "Download File" option in Amazfish. Now, Umlauts (äöü etc) are displayed correctly on my watch, although some not so common ones (just tested it with ĉ) are still displayed as [?].

**Comment by Thaodan** [comment]
I fixed the issue now by flashing the Latin version with the official app. There's no UTF-8 support as far as I know.
The issue isn't really because of this app but because of the watch, a faq entry would be good but that's it.

**Comment by jmlich** [comment]
I am trying transliteration in amazfish. I will be happy for feedback
https://github.com/piggz/harbour-amazfish/pull/272

**Comment by jmlich** [comment]
I think, this issue can be closed as https://github.com/piggz/harbour-amazfish/pull/272 is merged.

**Comment by piggz** [comment]
No, the code in #272 is just for the pinetimejf device, I think @Thaodan  has a bip or other amazfit device, so maybe we should apply the change at another level
