### ISSUE TITLE
[Device] Support for Amazfit Bip S

### ISSUE THREAD

**Issue by carmenfdezb** [piggz/harbour-amazfish#137]
Hi @piggz!!
I've bought an Amazfit Bip S recently and I would like to use it with Amazfish. I've cloned harbour-amazfish code and I've added "Amazfit Bip S" to devices by using biplitedevice (daemon/src/devicefactory.cpp and ui/qml/pages/PairSelectDeviceType.qml).
At the moment, it seems Amazfish works fine with my Bip S and I can set alarms, for example. Notifications doesn't work and I can't send watchfaces neither.
I'm not a developer and I don't know to do anything else. So I will appreciate a lot if you add support for Amazfit Bip S in next release.
Thank you for advance!

**Comment by piggz** [comment]
Ive added basic bip-s support on 1.7.0 using the GtsDevice.  Please try and see how it works.

**Comment by carmenfdezb** [comment]
I'm very sorry for the late answer. I have no problems to pair my Bip S with Amazfish, so thank you so much for add that watch model in v1.8.
Only "Download file" option doesn't work (I can select watchface file, but I can't send it to my watch, it says "Format not supported". I have issue #145 too.

**Comment by piggz** [comment]
Yeah, i deliberately dont allow download to devices I havnt tested so as not to breakanything!
If you want to head into the dange zone, you could try setting
dconf write /uk/co/piggz/amazfish/app/overridefwcheck true
To override some safety checks and see if that allows sending a watchface

**Comment by carmenfdezb** [comment]
> Yeah, i deliberately dont allow download to devices I havnt tested so as not to breakanything!
> If you want to head into the dange zone, you could try setting
> dconf write /uk/co/piggz/amazfish/app/overridefwcheck true
> To override some safety checks and see if that allows sending a watchface

I've tried dconf command, and "Format not supported" message isn't showed when I click on "Send" button, but it happens nothing.

**Comment by piggz** [comment]
ill close this as its now supported better.  Can you raise another issue just for the watchface download. pls.
