### ISSUE TITLE
SailfishOS 3.4.0.22

### ISSUE THREAD

**Issue by elkiaer-dk** [piggz/harbour-amazfish#138]
After the latest OS update it is not possible to download data from the band.

**Comment by piggz** [comment]
Yes, the issue is related to this:
https://forum.sailfishos.org/t/libicu-issues-across-sfos-releases/2561/11

At the moment im leaning towards only supporting official releases, with there being a delay for new releases until that is available on the OBS system.

**Comment by piggz** [comment]
New releases are for 3.4
