### ISSUE TITLE
Use application name and maybe icon from notifaction

### ISSUE THREAD

**Issue by Thaodan** [piggz/harbour-amazfish#14]
Currently the notication just lists app instead of the application name or something.

**Comment by piggz** [comment]
The bip has a fixed list of supported icons that can be used.  See alert notificationservice.h for what is allowed.  In alertnotificationservice.h, i map a bunch of apps I use to a more appropriate icon than the the 'App' icon, so changes need to go there to map the app name to an icon.

**Comment by Thaodan** [comment]
So there's no way  to convert the app  icon  to a lower format?
 I remember there was even an icon for whatsapp

**Comment by piggz** [comment]
there is a whatsapp icon, and i use it for whatsapp notifications
