### ISSUE TITLE
Receiving not working if Amazfish daemon is active

### ISSUE THREAD

**Issue by schm0lle** [piggz/harbour-amazfish#141]
The key-receiving did not work for me until I disabled the Amazfish daemon (see https://openrepos.net/content/piggz/amazfish). While the number of send keys constantly grew, the received keys stuck at 1. (I don't know where this one came from)

Device: Xperia XA2 Single SIM

**Comment by piggz** [comment]
what is this referring to?

**Comment by schm0lle** [comment]
In the first place to my lack of competence. Wanted to post this under https://github.com/llewelld/harbour-contrac. Sorry, will repost over there. Feel free to close.
