### ISSUE TITLE
[Device] Support for Mi Band 2

### ISSUE THREAD

**Issue by idnovic** [piggz/harbour-amazfish#15]
Hi I own a Mi Band 2.
Can you add support for it?
I can help with testing.
I use linux and sailfish os .

**Comment by idnovic** [comment]
Just found miband 2 in the src folder, you did not include it in the changelog.
Gonna test it out after I charged my miband.

**Comment by piggz** [comment]
its named that because the protocol is approx the same.

what is the name returned when scanning in sailfish BT dialog? currently i filter on Amazfit*, but it will be easy to change, you can just edit Pair-page.qml to try

**Comment by idnovic** [comment]
MI Band 2

above is the exacte return, first I get a mac addr4ess then the name above gets displayed (yes MI not Mi)

**Comment by idnovic** [comment]
I edited the settings and put "MI Band 2" in.
but your app is stuck at "Connecting to watch..."

**Comment by piggz** [comment]
Things you could try:
Make sure its not paired in the BT settings page
After trying to pair, what is the ConnectionState in th debug window?
When stuck, leave the pair window open, and switch back to the sailfish settings, and try and pair there, it might prompt my app to send the auth code

**Comment by idnovic** [comment]
steps do not seems to be syncroni.sed

**Comment by piggz** [comment]
App now supports band 2, 3, and 4.
