### ISSUE TITLE
Can't pair GTS with 1.8

### ISSUE THREAD

**Issue by je-nix** [piggz/harbour-amazfish#151]
Since the update to 1.8, I can't connect to my GTS anymore.
After the initial update, Amazfish could connect to the watch, but something was strange (UI of Amazfish was messed up, startup and scrolling through the stats meant that Amazfish was becoming unresponsive for some seconds). So I decided to do a fresh install of amazfish by removing the package, removing /home/nemo/.config/harbour-amafish und /home/nemo/.cache/harbour-amazfish.

Afterwards, the connection from amazfish to the GTS never worked again. I tried multiple watch resets and pairing with the Zepp app, even different ways to retrieve the auth code, but it always fails when amazfish tries to connect to the watch with "authfailed." By this point I am very confident that the error does not come from an incorrect auth code.
During pairing the watch with Zepp to retrieve a new auth code, it also installed a firmeware update on the watch, so I can't rule out that there were some changes regarding the auth mechanism.

If I forgot some files to completely wipe and reinstall amazfish, please let me know so I can try a fresh start.

I'll attach the debug log. The relevant log entries are:

Dec 24 09:10:55 XperiaX harbour-amazfishd[5889]: [D] unknown:0 - Got mi2 service
Dec 24 09:10:55 XperiaX harbour-amazfishd[5889]: [D] unknown:0 - Starting notify for  "00000009-0000-3512-2118-0009af100700"
Dec 24 09:10:55 XperiaX harbour-amazfishd[5889]: [D] unknown:0 - Writing request for auth number
Dec 24 09:10:55 XperiaX harbour-amazfishd[5889]: [D] unknown:0 - Crypt Byte: 128
Dec 24 09:10:55 XperiaX harbour-amazfishd[5889]: [D] unknown:0 - Writing to  "00000009-0000-3512-2118-0009af100700" : "8200020100"
Dec 24 09:10:55 XperiaX harbour-amazfishd[5889]: [D] unknown:0 - GTS with new FW
Dec 24 09:10:56 XperiaX harbour-amazfishd[5889]: [D] unknown:0 - Mi2Band Changed: "00000009-0000-3512-2118-0009af100700" "\x10\x82\x01\xA4(\xB9""A\x86\xB2\xCB;H\x9C\xBD\x95\xEA\xE6\x8FO"
Dec 24 09:10:56 XperiaX harbour-amazfishd[5889]: [D] unknown:0 - Received random auth number, sending encrypted auth number
Dec 24 09:10:56 XperiaX harbour-amazfishd[5889]: [D] unknown:0 - Writing to  "00000009-0000-3512-2118-0009af100700" : "8300dc632946e10180093cd9dff03018eab4"
Dec 24 09:10:56 XperiaX harbour-amazfishd[5889]: [D] unknown:0 - Mi2Band Changed: "00000009-0000-3512-2118-0009af100700" "\x10\x83\b"
Dec 24 09:10:56 XperiaX harbour-amazfishd[5889]: [D] unknown:0 - Unexpected data
Dec 24 09:10:56 XperiaX harbour-amazfishd[5889]: [D] unknown:0 - BipInterface::authenticated: false
Dec 24 09:10:56 XperiaX harbour-amazfishd[5889]: [D] unknown:0 - DeviceInterface::onConnectionStateChanged "authfailed"
Dec 24 09:10:56 XperiaX harbour-amazfishd[5889]: [D] unknown:0 - is firmware operation running: 0
Dec 24 09:10:56 XperiaX harbour-amazfishd[5889]: [D] unknown:0 - is miband operation running: 0
Dec 24 09:10:56 XperiaX harbour-amazfishd[5889]: [D] unknown:0 - is firmware operation running: 0
Dec 24 09:10:56 XperiaX harbour-amazfishd[5889]: [D] unknown:0 - is miband operation running: 0
Dec 24 09:10:56 XperiaX harbour-amazfishd[5889]: [D] unknown:0 - is firmware operation running: 0
Dec 24 09:10:56 XperiaX harbour-amazfishd[5889]: [D] unknown:0 - is miband operation running: 0
Dec 24 09:10:56 XperiaX i[4833]: [D] unknown:0 - void DaemonInterface::changeConnectionState()
Dec 24 09:10:56 XperiaX harbour-amazfishd[5889]: [D] unknown:0 - is firmware operation running: 0
Dec 24 09:10:56 XperiaX harbour-amazfishd[5889]: [D] unknown:0 - is miband operation running: 0
Dec 24 09:10:56 XperiaX i[4833]: [D] on_ConnectionStateChanged:32 - authfailed

**Comment by je-nix** [comment]
Well, this is strange. After restoring the old .config/harbour-amazfish/ folder and rebooting my phone to capture a fresh debug log to attach here, the connection suddenly works. But file transfer and data sync doesn't seem to work correctly.

My suspicion is that there is something fishy with my config as I've been using the same Amazfish profile for quite some time. What folders / files do I have to remove for a clean reinstall?

**Comment by piggz** [comment]
There the the folder in .config/harbour-amazfish ... there is also a dconf tree /uk/co/piggz/amazfish/with all the settings.

**Comment by je-nix** [comment]
Since I can't reproduce the issue (and don't want to risk another extensive debugging), I'll just close the issue for now. Thank you again for the support.
