### ISSUE TITLE
Database grows too large

### ISSUE THREAD

**Issue by vigejolla** [piggz/harbour-amazfish#155]
Storing sports activities in the database results in a large database, which after a while starts causing issues. My database was 129MB after about one year. 

Two possible solution ideas: 1) Don't store gpx in the database, it's enough to have the files in the filesystem 2) Allow to easily remove old activities.

**Comment by piggz** [comment]
Solution 1 implemented in 1.8.5.  I will probably also implement solution 2 at some point because during testing the new code, ive manage to amass a great number of duplicate entries in my database!

**Comment by piggz** [comment]
This is now fixed.  Database does not stroe raw GPX, juse the filename.  Also, there is now an option to delete records from the database.
