### ISSUE TITLE
Disconect watch on bluetooth disconect

### ISSUE THREAD

**Issue by Thaodan** [piggz/harbour-amazfish#16]
I noticed during testing that the app still is "connected" to the watch despite the watch is reseted to factory conditions.

**Comment by piggz** [comment]
do you mean there should be an option to delete the pairing?

**Comment by Thaodan** [comment]
No I mean when the watch is disconnected by bt the watch was still shown as connected

**Comment by piggz** [comment]
Yes, i found some cases where it shows connected and isnt, I think I can fix them.  A timer runs once a minute to re-check the connections, so it shouldnt show the incorrect state for too long.

**Comment by piggz** [comment]
Fixed in 0.7.5
