### ISSUE TITLE
[silica] Need more help with build instructions

### ISSUE THREAD

**Issue by b100dian** [piggz/harbour-amazfish#167]
I am not sure where qmake and make need to be run for developing on sailfish.
(that imples also where to install the dependencies).

Is it the host OS or the build VM? (SB2?)

For both my archlinux host and the SF build VM, I get:
```
Project MESSAGE: SailfishOS daemon build
Project MESSAGE: The project will be installed in /usr
Project ERROR: mlite5 development package not found
make: *** [Makefile:92: sub-daemon-make_first-ordered] Error 
```

at make.

Also how come
> Other dependencies can be installed from the Ubuntu package repositories

How would installing dependencies on the host machine help? Are these instructions to build the x86 binary?

**Comment by b100dian** [comment]
Here's what I got so far, maybe worth a readme update:

The build commands need to be issues on the build VM through `sb2`.

To get into the build machine (if started by Sailifsh IDE)
`ssh -l mersdk localhost -p 2222 -i ~/SailfishOS/vmshare/ssh/private_keys/engine/mersdk`

There, you use the `sb2` command to set one of the arm targets as default.

Next, you issue commands like `qmake` as `sb2 qmake`
The commands requiring root like `sb2 -R make install`

You need to add this repo `sb2 -R zypper ar http://repo.merproject.org/obs/home:/piggz:/kf5/sailfishos_3.4.0.24/ piggz` and `sb2 -R zypper refresh`
To install missing packages, as pointed out by build errors, use `sb2 -R zypper in mkcal-qt5-devel`

**Comment by piggz** [comment]
Docs updated, thanks
