### ISSUE TITLE
[Amazfit Bip S] Missed menu items

### ISSUE THREAD

**Issue by Alexus230** [piggz/harbour-amazfish#177]
Some menu items are currently missing, as i remember correctly:
- timer
- workout
- compass
- worldclock

**Comment by martinbook85** [comment]
Yes.

The only way I can enter workout is by setting long-press on button to start an exercise. When the exercise starts I push the button again to get to the workout menu.

Would be great to have those other features as well.

**Comment by piggz** [comment]
I think this is also fixed now, will be in 1.9.9

**Comment by 9nine9nine9** [comment]
On a related note, the menu entries don't line up (for me at least) on the Mi Band 4.
Settings Entry | Watch Entry
------ | -------
Timer | Status
Alarms | More
Status | Notifications
Weather | Workout
Activity | Weather
Compass | Heart Rate
Status | Notifications
AliPay | Cards
Settings | Watch face

I believe that the AliPay option is correct, although opening it on my non-NFC band causes it to reboot.
Enabling settings seems to have no effect (I don't believe it's possible to disable the watch face with the default firmware)

**Comment by piggz** [comment]
Try 2.0.0 and see if any are still mssing...they may be

**Comment by juanro49** [comment]
Hi! I recently bought an Amazfit Bip S to track my bike routes instead using mobile GPS, but I see that all menu options are not showing, only status, heart rate, PAI and Workout.

The timer, compass, weather, alarm, music, worldclock and settings (needed to turn off or reset the watch among other things) are missing.

I'm using latest Amazfish version (2.0.3-1.1.1.jolla armv7a) in chum repos

**Comment by piggz** [comment]
Go to settings > device > huami display items.  in there you can show/hide/reorder the menu items.
