### ISSUE TITLE
make whitelisting resources configurable via file or appendable in app

### ISSUE THREAD

**Issue by maslovalex** [piggz/harbour-amazfish#178]
ATM, it seems like files allowed to be sent to the device are hard coded into the sources (see  bipfirmwareinfo.cpp for the Bip)

As far as I understand there is no way to flash anything not in that file.

Making it possible to flash anything in the app may be a bit too dangerous for the ordinary user, but why not to make whose whitelists configurable via some file(s) maybe?

Those who want to "play" with it could edit the file and be aware of what they are doing.
Also no need to wait when some particular Fw/Res/Font added into the white list.

It is easier than having whole build process setup to modify sources and build your own version of the application.

**Comment by piggz** [comment]
There is already an option
dcont write /uk/co/piggz/amazfish/app/overridefwcheck 1
See if that works for you ... but dont complain if you break something :D

**Comment by maslovalex** [comment]
thx, seems to have no effect.
Using `dconf write /uk/co/piggz/amazfish/app/overridefwcheck 1` or `true` keeps saying "File not supported on this device" when I press `Send button`.

Stop/start background service does not help

**Comment by maslovalex** [comment]
But editing `~/.config/harbour-amazfish/harbour-amazfish.conf` seems to have an effect. `dconf` setting still left to be 1 (not sure if that one used by app or daemon at all)

**Comment by maslovalex** [comment]
By adding  `overridefwcheck=true` into the `[app]` section of `~/.config/harbour-amazfish/harbour-amazfish.conf` I was able to flash BipOS 0.5.4 into may Amazfit Bip.

thx.

**Comment by piggz** [comment]
Ah, you were not running in sailfish?

**Comment by maslovalex** [comment]
I was. 4.0.1.48 XA2

**Comment by piggz** [comment]
Ah rats, a bug in the builds .. sailfish isnt supposed to use the config file ... will be fixed in next release.
