### ISSUE TITLE
Firmware Weather string and AGPS

### ISSUE THREAD

**Issue by martinbook85** [piggz/harbour-amazfish#182]
Amazfish tells me now and then that the Firmware on the watch is compatible with weather string. What does that mean?

My Amazfit Bip S tells me that I need to upgrade AGPS for the GPS to work better. Can I do that through Amazfish?

**Comment by piggz** [comment]
I can probably remove that message, its more from early debugging for myself.
The AGPS is a pain.  There is a tool called huami_token.py which can get the AGPS files, but, atleast my GTS on its updated firmware needs a different AGPS file which is doesnt download yet.

**Comment by piggz** [comment]
Ive added documentation here on how to handle AGPS https://github.com/piggz/harbour-amazfish/wiki/How-To-update-AGPS
