### ISSUE TITLE
Setting alarm is not working

### ISSUE THREAD

**Issue by martinbook85** [piggz/harbour-amazfish#188]
Using 
Amazfit Bip S
Sailfish XA2 Ultra

Desired result:
Setting times for alarms on the Amazfish app transfers to watch and goes off if activated.

Real result:
Alarms set on app, not seen in the Alarm settings on the watch. Thus alarms on the watch don't work.

**Comment by piggz** [comment]
Is this still an issue?

**Comment by martinbook85** [comment]
I do not even remember posting this. Maybe it was for my old band.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by carmenfdezb** [comment]
I have exactly this issue. I use the last version of Amazfish installed from chum and I have a Amazfit BIP S too. I think this feature was working in 2.1 or at least I've noticed about this issue when I updated the app to 2.2.

**Comment by carmenfdezb** [comment]
It's working fine again since v2.2.4 :)
