### ISSUE TITLE
SF Kvarken libicui18n.so.66 missing

### ISSUE THREAD

**Issue by Termitebug** [piggz/harbour-amazfish#192]
Hi, I was forced to uninstall Amazfish before upgrading to SFOS Kvarken upgrade. After the process I noticed that app dependencies were broken.
Can't install this now. Any help?

Edit: With 2.0.2-1 version & SF 4.1 install is again possible. Issue is resolved, thank you for your work!

**Comment by OhneZ007** [comment]
I also have the same problem. It is not possible to install the app.
