### ISSUE TITLE
Build instructions for Debian (Mobian)?

### ISSUE THREAD

**Issue by girlwithnoname** [piggz/harbour-amazfish#197]
I would like to build the app for Mobian (on Oneplus 6T, so aarch64). How to start? Is there any documentation that is not for Sailfish? I haven't found anything. Thanks for helping!

**Comment by piggz** [comment]
See https://github.com/piggz/harbour-amazfish/blob/master/documentation/build-instructions.md which covers sailfish and ubuntu, you should be able to figure it out from there, if you have any specifics, get back to me.

**Comment by girlwithnoname** [comment]
Thanks. Will do.

**Comment by girlwithnoname** [comment]
I managed to successfully build and install. Unfortunately the UI won't start.
I get the following:
droidian@droidian:~/git/harbour-amazfish/build$ harbour-amazfish-ui 
("/usr/local/share/icons", "/usr/share/icons", ":/icons") ("/usr/share/pixmaps", ":qml/custom-icons")
Connecting to daemon signals
void DaemonInterface::changeConnectionState()
No drivers found
O2ReplyServer: Starting
qml: Checking if feature is supported: 1 false
qml: Checking if feature is supported: 1 false
qml: Checking if feature is supported: 8 false
qml: Checking if feature is supported: 8 false
qml: Checking if feature is supported: 8 false
qrc:/qml/pages/FirstPage.qml:90:13: QML BusyIndicatorSmallPL: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
file:///usr/lib/aarch64-linux-gnu/qt5/qml/org/kde/kirigami.2/private/RefreshableScrollView.qml:137:13: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
Cannot find EGLConfig, returning null config
qt.qpa.wayland: Non-blocking swap buffers not supported. Subsurface rendering can be affected. It may also cause the event loop to freeze in some situations
harbour-amazfish-ui: symbol lookup error: /usr/lib/aarch64-linux-gnu/qt5/plugins/wayland-graphics-integration-client/libqt-plugin-wayland-egl.so: undefined symbol: eglCreatePlatformWindowSurface

Any idea?

**Comment by piggz** [comment]
The no drivers issues will mean that you dont have the kdb-drivers-sqlite package installed, but that wont stop it opening.  The undefined symbol looks serious, what device is this on?

I found a forum thread where some got it working on pinephone/mobian, so it should work ok. https://forum.pine64.org/printthread.php?tid=13122

**Comment by girlwithnoname** [comment]
To answer myself:
I unset unset QT_QPA_PLATFORM and it works. But the interface is broken... all graphics and the arrows are missing and the menus are only accessible when I turn the device into landscape mode. Plus tapping on user settings won't do anything. Did I do anything wrong? Thanks again for helping me.

**Comment by piggz** [comment]
Can you send screenshots?  Please be aware that the kirigami interface is not tested as mush as the sailfish interface, especially not on a mobile device, i have only tested in on my local desktop.  Ive had PRs in the past to fix UI bugs on kirigami, from KDE devs, so, I can only assume it works ok for them.  The icons are supposed to get compiled in as resources, does it look like that happening?

**Comment by girlwithnoname** [comment]
Sorry, apparently we answered in the same moment and I only saw your reply now. Github doesn't take my pictures... I will take a deeper look again in the next hours.

**Comment by girlwithnoname** [comment]
Here's the screenshot.
![Bildschirmfoto vom 2021-07-27 17-37-35](https://user-images.githubusercontent.com/41264969/127191215-cef21361-a800-419a-b17e-d460c5068a92.jpg)

**Comment by girlwithnoname** [comment]
More information: this is Droidian (like Mobian) on the Oneplus 6T (as Mobian itself isn't that usable yet on this device). I experienced the same bugs as is written down on the site you provided (https://forum.pine64.org/printthread.php?tid=13122). Still I'm happy and I even received some messages on my GTS :-)

**Comment by piggz** [comment]
I guess most users are using pinetimes ... as youre a GTS user, you would benefit by also installing the mapbox QML component, so that you can view your tracked activities.

**Comment by girlwithnoname** [comment]
Thanks, that is useful. Can I do anything to bring in the icons? They are in the build folder, so I have no clue why they are missing...

**Comment by piggz** [comment]
is there anything in the logs/output from the UI?

**Comment by girlwithnoname** [comment]
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
("/usr/local/share/icons", "/usr/share/icons", ":/icons") (":qml/custom-icons")
Connecting to daemon signals
void DaemonInterface::changeConnectionState()
DRIVERS:  ("org.kde.kdb.sqlite")
Database is:  "/home/droidian/.local/share/harbour-amazfish/harbour-amazfish/amazfish.kexi"
KDbConnection object created.
KDbConnection::connect() OK.
O2ReplyServer: Starting
qml: Checking if feature is supported: 1 false
qml: Checking if feature is supported: 1 false
qml: Checking if feature is supported: 8 false
qml: Checking if feature is supported: 8 false
qml: Checking if feature is supported: 8 false
qrc:/qml/pages/FirstPage.qml:90:13: QML BusyIndicatorSmallPL: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
file:///usr/lib/aarch64-linux-gnu/qt5/qml/org/kde/kirigami.2/private/RefreshableScrollView.qml:137:13: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/aarch64-linux-gnu/qt5/qml/org/kde/kirigami.2/private/ActionButton.qml:221:13: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/aarch64-linux-gnu/qt5/qml/org/kde/kirigami.2/ActionToolBar.qml:110:18: QML ToolBarLayout: Binding loop detected for property "actions"
file:///usr/lib/aarch64-linux-gnu/qt5/qml/org/kde/kirigami.2/templates/AbstractApplicationHeader.qml:162:9: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/aarch64-linux-gnu/qt5/qml/org/kde/kirigami.2/templates/AbstractApplicationHeader.qml:99:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/aarch64-linux-gnu/qt5/qml/org/kde/kirigami.2/templates/AbstractApplicationHeader.qml:139:9: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/qml/harbour-amazfish.qml:175:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/qml/harbour-amazfish.qml:53:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/aarch64-linux-gnu/qt5/qml/org/kde/kirigami.2/templates/OverlayDrawer.qml:284:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/qml/components/platform/StackPL.qml:33:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/qml/components/platform/StackPL.qml:33:5: QML Connections: Cannot assign to non-existent property "onInfoActiveChanged"
file:///usr/lib/aarch64-linux-gnu/qt5/qml/org/kde/kirigami.2/templates/AbstractApplicationHeader.qml:162:9: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/aarch64-linux-gnu/qt5/qml/org/kde/kirigami.2/templates/AbstractApplicationHeader.qml:139:9: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/aarch64-linux-gnu/qt5/qml/org/kde/kirigami.2/templates/AbstractApplicationHeader.qml:99:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/qml/components/platform/StackPL.qml:38:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/qml/components/platform/PagePL.qml:49: TypeError: Cannot read property 'title' of undefined
qrc:/qml/pages/FirstPage.qml:82: ReferenceError: txtMessage is not defined
qml: authenticated
qml: Supported features: 511
qml: Checking if feature is supported: 1 true
qml: Checking if feature is supported: 1 true
qml: Checking if feature is supported: 8 true
qml: Checking if feature is supported: 8 true
qml: Checking if feature is supported: 8 true
qml: Supported features 511
QSGTextureAtlas: texture atlas allocation failed, code=501
qml: Checking if feature is supported: 8 true
qml: Checking if feature is supported: 8 true
qml: Checking if feature is supported: 8 true
qml: Checking if feature is supported: 1 true
qml: Checking if feature is supported: 1 true
qml: Information changed 3 PRTM74 0300040027
qml: Information changed 6 19439,3aa3392,135
qml: Information changed 2 V0.36.19.20
qml: Information changed 1 V0.1.2.03
qml: Information changed 4 ɠD��EU
qml: Information changed 5 W.
qml: Information changed 7 47
qrc:/qml/pages/FirstPage.qml:82: ReferenceError: txtMessage is not defined
qrc:/qml/components/platform/PagePL.qml:49: TypeError: Cannot read property 'title' of undefined
qml: Start timer triggered
file:///usr/lib/aarch64-linux-gnu/qt5/qml/org/kde/kirigami.2/private/RefreshableScrollView.qml:137:13: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/aarch64-linux-gnu/qt5/qml/org/kde/kirigami.2/private/ActionButton.qml:221:13: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
"SELECT date(timestamp_dt), sum(steps) FROM mi_band_activity WHERE date(timestamp_dt) >= date('2021-07-27T00:00:00','-10 day') AND timestamp_dt <= '2021-07-27T23:59:59' GROUP BY date(timestamp_dt) ORDER BY timestamp_dt ASC"
Error executing query
qrc:/qml/harbour-amazfish.qml:29: TypeError: Cannot read property 'connectionState' of null
qrc:/qml/pages/FirstPage.qml:92: TypeError: Cannot read property 'operationRunning' of null
qrc:/qml/pages/FirstPage.qml:69: TypeError: Cannot read property 'operationRunning' of null
qrc:/qml/components/Graph.qml:6: TypeError: Cannot call method 'dataSource' of null
qrc:/qml/components/DownloadDataMenuItem.qml:7: TypeError: Cannot read property 'connectionState' of null

**Comment by girlwithnoname** [comment]
That happens when I start it from terminal. Had to pipe this into a file, that may explain the strange character in the text.
