### ISSUE TITLE
Connection cannot be established again after a while.

### ISSUE THREAD

**Issue by gomerust** [piggz/harbour-amazfish#2]
I am using the Bip with Fairphone 2 release 2.1.4.14 
Is there a way to get debug information that could help? 
Should the Watch be pared within the app and not via the system?
How can i help?

**Comment by gomerust** [comment]
Ah thanks for that. i was wondering if this was about unstable bluez5 implementation in the fp2. That helped, and i can live with that :D at least for a while.
i think this happens more often, when i connect from the android device and back... maybe the watch gets confused with the sailfish implementation then. When this happens, the Android connection still works fine.

**Comment by gomerust** [comment]
That sounds great! am happy to hear that!

**Comment by piggz** [comment]
Can you try the latest version?

**Comment by piggz** [comment]
This should be resolved with the re-write
