### ISSUE TITLE
Add amazfit GTS 2 support

### ISSUE THREAD

**Issue by miqu** [piggz/harbour-amazfish#200]
Gadgetbridge has added support for GTS2 amd GTR2 so could we use the help of their code to add support for newer devices to Amazfish?

I happen to own a GTS2 and so would have an interest to help on that device.

At the moment it pairs but doesnt connect. Connection Code retrieved from server with huafetcher.

**Comment by piggz** [comment]
can you message me on telegram @adampigg to try a test build

**Comment by miqu** [comment]
Missed this will do.

ma 3. tammik. 2022 klo 20.48 Adam Pigg ***@***.***) kirjoitti:

**Comment by piggz** [comment]
This is now fixed in 2.0.8 with a custom build of bluez5 from https://build.merproject.org/project/show/home:piggz:harbour-amazfish-dev
