### ISSUE TITLE
InfiniTime motion service: is new release coming?

### ISSUE THREAD

**Issue by akutuzov** [piggz/harbour-amazfish#204]
It seems that the support for InfiniTime motion service (step count) is [finally added](https://github.com/piggz/harbour-amazfish/commit/943c4d5e4168dfba64221f72cb417750fe47f4f7)

However, it is not clear to me how to actually install this updated version of AmazFish. Apparently, it is not yet there on OpenRepos.
Are there any plans to publish a new release?

**Comment by bowao** [comment]
_**Amazfish from 2.0.3 is now ONLY distributed in the "chum" repository!**_

You have to add the "chum" repository
Then amazfish can be installed via `pkcon install harbour-amazfish`

**Comment by akutuzov** [comment]
Thanks @bowao 
Can you point me to a step-by-step instruction on how exactly to add the "chum" repository on Sailfish OS?
The [official documentation](https://github.com/sailfishos-chum/main) is extremely vague.

**Comment by piggz** [comment]
@atlochowski easiest way is to follow the instructions, and go to chumrpm.netlify.app. in browser, this will give links to the RPMs to install for the repo and gui.  You may need to pkcon refresh, but it will work

**Comment by piggz** [comment]
@akutuzov also, if you can think of any way to improve the documentation, please file an issue against the project and will will improve it.

**Comment by atlochowski** [comment]
@piggz I have nothing to do with this topic.

**Comment by piggz** [comment]
> @piggz I have nothing to do with this topic.

Sorry, the @ completion messed up :)
