### ISSUE TITLE
GTS 2 doesn't connect through the app

### ISSUE THREAD

**Issue by hiroi-p** [piggz/harbour-amazfish#208]
Hi, I've just bought a GTS 2 to use with my Xperia II running Sailfishos. I have the watch paired through Bluetooth but when I try to connect it through Amazfish the Bluetooth icon loads fine but then the watch icon stays in loading until both disappear. I did fetch the auth key and typed it when I was prompted without the 0x from the beginning but it doesn't work. I tried reboots on both the watch and the phone but to no avail. 

Do you know how to fix this? I really want to get this watch working on my Sailfish device..

**Comment by HiroiOwO** [comment]
These are the logs when I try to connect to it

![Screenshot_20211122_002](https://user-images.githubusercontent.com/64701225/142804242-20e68d39-369e-487b-9a7b-071f7f782ee0.png)

**Comment by piggz** [comment]
Hi, thanks for the feedback, as i dont have a GTS2 i couldnt test.

Can you send logs from the daemon:
devel-su
journalctl | grep amazfish > amazfishlog.txt

then post the file here, thanks

**Comment by HiroiOwO** [comment]
Sorry it took so long, I have tried to downgrade the software to 4.0.1.5 from the latest, sadly I still have the same problem, here are the logs, I hope it helps!
[amazfishlog1.txt](https://github.com/piggz/harbour-amazfish/files/7582696/amazfishlog1.txt)

**Comment by piggz** [comment]
Ok, what is the Amazfish version (rpm -qi harbour-amazfish)and can you tell me the name the GTS2 shows in sailfish BT settings (exact case/spelling) thanks

**Comment by HiroiOwO** [comment]
The Amazfish version is 2.0.3.
I am not sure if this is normal with the previous watches, but I get 2 devices instead of a single one. There is "Amazfit GTS 2" and "Amazfit GTS 2 09E5". The difference between them is that the 09E5 comes up when I try to pair from the watch to the phone.

**Comment by HiroiOwO** [comment]
It did work, since know I don't get the unknown device error, but I it still won't work, I got some new logs to work with:
[amazfish.txt](https://github.com/piggz/harbour-amazfish/files/7583605/amazfish.txt)

**Comment by HiroiOwO** [comment]
Any updates?

**Comment by piggz** [comment]
thinking

**Comment by HiroiOwO** [comment]
Were you able to track down the problem?

**Comment by piggz** [comment]
im working on a idea

**Comment by piggz** [comment]
So, when i use the GTS2 code against my GTS, it works ok.
Could you do the following:
pair the device in the sailfish BT settings page
as root, systemctl stop harbour-amazfish
as user, run harbour-amazfishd and send all the logs it generates.

thanks

**Comment by HiroiOwO** [comment]
I couldn't stop it because it didn't find the service but here are the logs:

[amazfishlogs.txt](https://github.com/piggz/harbour-amazfish/files/7631311/amazfishlogs.txt)

**Comment by piggz** [comment]
You need to stop the service and do it again....things dont works so well with 2 daemons runing.

My fault for bad instructions
as user
systemctl --user stop harbour-amazfish

the run the daemon manually and post logs

**Comment by HiroiOwO** [comment]
This time the command worked, here are the logs:
[amazfishlogs.txt](https://github.com/piggz/harbour-amazfish/files/7636692/amazfishlogs.txt)

**Comment by piggz** [comment]
Hi, that log doesnt make a whole lot of sense

can you leave the daemon running, then in the BT settings page, try pairing the watch, then pair it using the amazfish UI, and send the logs

**Comment by HiroiOwO** [comment]
I did all the things that you requested and here are the logs:
[amazfishlogs.txt](https://github.com/piggz/harbour-amazfish/files/7636986/amazfishlogs.txt)

**Comment by piggz** [comment]
I discussed with the gadget-bridge dev, and he wondered if you had the watch paired with another phone, and had enabled the "do not connect to other device" option?

**Comment by HiroiOwO** [comment]
I did have it connected to another phone in order to get the token, but I checked into the zepp app and that option was turned off. I even enabled the "discoverable" mode that said it would allow info to go to the 3rd party apps but the same problem persists.

**Comment by HiroiOwO** [comment]
I just tried to connect it to the GadgetBridge app on my other phone and that worked flawlessly, so I don't think it's the watch's fault. Do you have any other ideas or should I just return this watch and get a GTS 1 or other watch instead?

**Comment by HiroiOwO** [comment]
If I don't get a response soon, I will proceed with the return process and get a GTS 1 since if I don't hurry, the return windows will close.

**Comment by piggz** [comment]
Ok.... Im sure I could get it working with a device, its just quite difficult to remote-debug such things!

**Comment by HiroiOwO** [comment]
It's fine, I understand and I would love to help you debug this further, but the return period is expiring so yeah. Good luck in the future tho!

**Comment by HiroiOwO** [comment]
The GTS 1 has arrived and it works with no problems. The way the software feels is pretty different tbh and the build quality as well, but the battery seems to be way better on the GTS 1, with the GTS 2 I was getting 2 days at best, while on the GTS 1 it barely dropped in the days that I was using it.

Anyway, good luck in the future, I will keep a close eye on this project, I think it's pretty neat.

**Comment by ThongSong7** [comment]
GTS2 Owner: how can I use your software?  It no connecty, no worky

**Comment by piggz** [comment]
@ThongSong7 can you ping me on telegram, @adampigg and i can send you a version to test

**Comment by piggz** [comment]
ANy update/logs available?

**Comment by piggz** [comment]
This is now fixed in 2.0.8 with a custom build of bluez5 available from https://build.merproject.org/project/show/home:piggz:harbour-amazfish-dev
