### ISSUE TITLE
Support for media controls

### ISSUE THREAD

**Issue by sailfishmods** [piggz/harbour-amazfish#21]
is it possible to add media controls like this:
https://www.youtube.com/watch?time_continue=3&v=gBVEoHB0Yj8

2 times = skip music forward 
3 times = skip music backward

**Comment by piggz** [comment]
probably...im sure i can get device events quite easily, would just need converted into dbus commands after that

**Comment by Thaodan** [comment]
There's mpris proxy already. Maybe you could get data from there

**Comment by sailfishmods** [comment]
nope, not working :(

**Comment by Thaodan** [comment]
I don't said it works out if the box.
But it already provides a interface to mpris , this needs to be mapped to the bip specific service.
If bip would support Bluetooth media controls w
This would be not needed.

**Comment by explit7** [comment]
That would be indeed a good feature

**Comment by piggz** [comment]
i have this working in my dev build :)

**Comment by piggz** [comment]
https://twitter.com/adampigg/status/1018962191842758656

**Comment by piggz** [comment]
Closed as 0.7.1 released
