### ISSUE TITLE
Doesn't work in 4.4.0.58 with Sailjail

### ISSUE THREAD

**Issue by juanro49** [piggz/harbour-amazfish#219]
Hi!

In the last version 4.4.0.58, Amazfish can't connect with band (Amazfish Bip S). Instead of "connect to watch", "Disconnect from watch" is displayed but it is not connected.

if I start Amazfish from terminal or include in the .desktop file the following, it connects, and everything works
[X-Sailjail]
Sandboxing=Disabled

**Comment by cintema** [comment]
For me activity sync works when amazfish-ui is started from terminal.
I played around with sailjail as well but couldn't get it to work properly by granting dedicated permissions (e.g. AppLauncher allows amazfish-ui to launch its background service). Still no data is then transferred, though. Probably this is related to non-standard data storage?
It would really be cool if it was possible to get sailjail working with amazfish.

**Comment by elkiaer-dk** [comment]
Connection OK
Live data OK
Data can not be downloaded AND data is percent even if amazfish.kexi is not exciting.

**Comment by elkiaer-dk** [comment]
The .kexi file is there, it is the filebowser where there is some issues with 4.4.0.58.
The .kexi file can be found using the Terminal.

**Comment by piggz** [comment]
Is this still an issue? The last 2 released should have worked.

**Comment by juanro49** [comment]
> Is this still an issue? The last 2 released should have worked.

with the last version, it work fine witouth editing .desktop file. Thanks!!

**Comment by cintema** [comment]
I can also confirm it works now.
