### ISSUE TITLE
Skiing icon missing in activity view.

### ISSUE THREAD

**Issue by cintema** [piggz/harbour-amazfish#220]
Just noted that skiing activity (amazfit GTS) is displayed correctly but doesn't feature a dedicated icon unlike the other activities.

**Comment by piggz** [comment]
Ill add this ... however, im not sure i can add icons for all the ones on the new devices like GTR2, they have about a hundred activity types, including 10 types of "combat sports" !

**Comment by cintema** [comment]
Oh, haha I see. Maybe a "universal" icons for some subcatagories will do?
Great you add skiing though, for me that's the main sports activity I use the watch for :-) Thank you very much!

**Comment by cintema** [comment]
Hi again,
just for the record (I thing you didn't find the time to fix the skiing icon yet, no worrys).
Skiing activities are showing up in strava in the cycling categorie (not alpine skiing). There is a ski touring activity applicable in strava as well (but not on the watch). Probably alpine skiing is more common (but maybe sport trackers are more often used in ski touring? I don't know?).
But actually, even if you are in ski touring you may still end up alpine skiing pretty often (at least that's valid for me :-)) and I'd suggest linking the alpine skiing activity in strava to the skiing activity in the watch.
Thanks again!

**Comment by piggz** [comment]
Thanks ... ill add this too... from my own perspective my new watch has an activity type for Trail Running, and that also gets uploaded to strava incorrectly

**Comment by piggz** [comment]
Added in 2.0.8 (i hope!)

**Comment by cintema** [comment]
Hi again, unfortunately skiing doesn't work properly for me yet. Still no icon in amazfish, activities still appear as cycling when syncing to strava.
Maybe I can send some activity data to analyse?
Thanks, Chris
