### ISSUE TITLE
No data graph after daylight saving time change

### ISSUE THREAD

**Issue by juanro49** [piggz/harbour-amazfish#222]
Following the time change on March 27th by advancing the clock by one hour, the graphical data is no longer displayed in Amazfish and the graphical data of March 27th is corrupted.

I attached graphs of days 26, 27 and 28

![Captura_20220331_002](https://user-images.githubusercontent.com/11600804/161143584-01537549-b893-46bf-b858-e120618f7bd4.png)
![Captura_20220331_003](https://user-images.githubusercontent.com/11600804/161143589-9a8e8243-67c5-4c1f-9b1f-86cd5da2fd58.png)
![Captura_20220331_004](https://user-images.githubusercontent.com/11600804/161143598-273c9230-cf64-473c-9bc2-6818b90c3bce.png)
![Captura_20220331_005](https://user-images.githubusercontent.com/11600804/161143600-462b0799-9d5b-4d5b-b40a-1df26e13d2dd.png)
![Captura_20220331_006](https://user-images.githubusercontent.com/11600804/161143601-66eb3c3f-dc0e-459c-96cd-e01a83cfa8e3.png)
![Captura_20220331_007](https://user-images.githubusercontent.com/11600804/161143606-980bace5-8d62-49ae-ac0d-714debb23de1.png)
![Captura_20220331_008](https://user-images.githubusercontent.com/11600804/161143610-cc332c21-f981-41ac-a418-b9db01c343c6.png)
![Captura_20220331_009](https://user-images.githubusercontent.com/11600804/161143613-9a3291f3-921a-4d92-8db7-ca40df185aac.png)

**Comment by piggz** [comment]
Hi

Known issue.  There is a workaround, in the Debug menu, you can toggle the last sync time by +- a few hours and it will work again, the the one that starts with A:

**Comment by juanro49** [comment]
> 

thanks! I try this and now work fine! 😋
