### ISSUE TITLE
[Amazfit GTR] [SFOS4.4.0.58] Data not stored in harbour-amazfish app

### ISSUE THREAD

**Issue by kostas12ldb** [piggz/harbour-amazfish#224]
I have a GTR paired with my Xperia 10 II, running on Sailfish OS 4.4.0.58.

Since the last OS update, although the data are shown in real-time within the app (current steps, current hr), they are not stored (history for sleep, steps, hr are blank, showing "no data"). Moreover, I cannot send a watchface to the device anymore ("File not supported on this device").
The function to download a recorded exercise works OK, and my previous exercises are shown in the list.
![Στιγμιότυπο_20220425_003](https://user-images.githubusercontent.com/104370126/165105528-19f033dc-a568-4dc3-8323-b1bd5d2d0801.png)
![Στιγμιότυπο_20220425_002](https://user-images.githubusercontent.com/104370126/165105538-f406bfa7-2328-49f1-983b-262391e496ef.png)

**Comment by piggz** [comment]
Try uninstalling the current version, an installing the latest version from Chum.

**Comment by OhneZ007** [comment]
The transfer of A-GPS data to the watch does not work either. 
However, my other data from the watch is saved.

**Comment by kostas12ldb** [comment]
@OhneZ007 , the A-GPS upload function stopped working a while back, the only solution is to connect once a week to the Zepp app, and let it update it, otherwise you do not get any GPS signal on the watch (unfortunately).

**Comment by OhneZ007** [comment]
I also had the same problem with saving.
With me it always occurred when the time (summer / winter time) has been changed.
In the debug mode possibly set the time times by 1 - 2 h forward. Maybe it helps.

**Comment by kostas12ldb** [comment]
> I also had the same problem with saving. With me it always occurred when the time (summer / winter time) has been changed. In the debug mode possibly set the time times by 1 - 2 h forward. Maybe it helps.

I do not believe it! 😄
@OhneZ007, that was the actual solution!
My device was actually set to "Automatic" date and time, and, for some reason, after the 4.4.0.58 update, the time zone was changed to Helsinki!
Changed it back to correct time zone, and everything went back to normal.
Steffen, my friend, thank you so much for that!
