### ISSUE TITLE
Issues Amazfit GTR2 pairing on a Sony Xperia X dual SIM

### ISSUE THREAD

**Issue by Thermo41** [piggz/harbour-amazfish#225]
Hi,

  I seem to be unable to pair my watch (Amazfit GTR2) with amazfish on a sony Xperia X dual SIM, Sailfish OS ver: 4.4.0.58.

I tried everything I have understood from your documents and those you point out, including :
- restart bluetooth on the phone, 
- reboot phone
- reset watch to factory settings, eventually it leaves firmware at release 6.4.1.1 - as after updating from the old android phone I used to pair it initially.
- etc.

  I also tested on an android tablet the pairing works with gadgetbridge the same authentication key (I obtained through several methods) does work.

  Has anyone got a similar issue on the same phone model?
  Any hint ? 

   One point I am unsure of:  the bluez patch mentioned about GTS2/GTR2, is it included in recent OS versions or has it to be applied? If the latter, I am not sure how.

Regards
Dominique

**Comment by piggz** [comment]
Hi, no the bluez patches are not yet in Sailfish and a modified bluez must be installed first.
In a terminal add the repoitory for your architecture, either
ssu ar amazfish-dev https://build.merproject.org/project/repository_state/home:piggz:harbour-amazfish-dev/sailfish_4.4.0.58_armv7hl
or
ssu ar amazfish-dev https://build.merproject.org/project/repository_state/home:piggz:harbour-amazfish-dev/sailfish_4.4.0.58_aarch64
then
ssu ur
zypper ref
zypper up bluez5 (you may need some flags to force zypper to do the update)

**Comment by Thermo41** [comment]
Hi

  Sorry about the delay.
 That does not seem to resolve the issue completely: I finished by
pairing with teh watch but never succeeded in connecting to it.

 Quick question: there are other blues5 related packages that blues5
itself, should any of them be installed as well ?

Regards
Dominique

Le samedi 07 mai 2022 à 14:12 -0700, Adam Pigg a écrit :

**Comment by piggz** [comment]
Yes, you need to install the bluez5 version from the repo above until the version in sailfish is updated with the fix.

**Comment by piggz** [comment]
This should all be fine in Sailfish 4.4 and 4.5
