### ISSUE TITLE
Using DFU zip for InfiniTime

### ISSUE THREAD

**Issue by Riksu9000** [piggz/harbour-amazfish#226]
Currently InfiniTime provides a DFU zip and a binary image in releases. Most companion apps use the DFU file. We would like to reduce the fragmentation and have every companion app work with the DFU file. I haven't used this app, but I've heard that it only supports the bin file, and it is blocking us from removing the binaries from releases.

So my request is for this app to support flashing InfiniTIme with the DFU zip, thanks.

**Comment by piggz** [comment]
This is currently being worked on
