### ISSUE TITLE
No further Informations on App-Cover

### ISSUE THREAD

**Issue by FingusDE** [piggz/harbour-amazfish#229]
While it seems in the cover.qml showing further informations on App-Cover is implemented (Smartwatch Battery-State, Steps...etc), it doesn´t show any other Informations like the "Amazfish"-Title and a static Clock-Background.

**Comment by piggz** [comment]
This came around when moving to generic components to support standard linux desktops.  I should look for a way to bring this back to the sailfish version

**Comment by FingusDE** [comment]
Is it complicated to route the needed Data to the Cover-Data-Model?

**Comment by jmlich** [comment]
I hope this was fixed by https://github.com/piggz/harbour-amazfish/pull/410
