### ISSUE TITLE
Current Temperature String is in Wrong Format

### ISSUE THREAD

**Issue by FingusDE** [piggz/harbour-amazfish#230]
The Current Temperature-String gives this Format: 

Current_Temp/Max_Temp_Today

Which doen´t work with the Watchface on the Amazfit-Smartwatches.
The Temperature-Field on the Watchface leave blank then. 

So it seems to expect just Current_Temp.

**Comment by piggz** [comment]
This appears to work ok on my GTR2 and GTS .. what specific device are you having trouble with?

**Comment by FingusDE** [comment]
I´m using a GTS with Firmware v0.1.1.17.

While the first inbuild Warchface with digital Display shows 23/23 at the weather-string the second inbuild Watchface with the Analog-Clock shows only -- at the Temperature-Field. And so many Custom Watchfaces does. It seems they can´t handle more then 3 chars.

**Comment by FingusDE** [comment]
I have found out that the Update-Intervall was set to maximum  (Refesh Weather all 120 Minutes) and in this timeslot my device had no internet-connection, so i really never got update of the "current" Temperature.

I increase it to 15 Minute-Intervall and now it works most of the time!
