### ISSUE TITLE
Pinetime not syncing steps on Xperia 10 II

### ISSUE THREAD

**Issue by dvidebaek** [piggz/harbour-amazfish#235]
I have a Pinetime with Infinitime v. 1.10. The Pinetime is connected to the phone Xperia 10 II, but the steps is not syncing to the phone. Battery percentage indicator always shows 0 %.

SFOS is the newest version 4.4.0.68

**Comment by jmlich** [comment]
battery level was fixed in https://github.com/piggz/harbour-amazfish/pull/271
The steps counter seems to be showing only when value is updated (application doesn't transfer last reading from daemon)

**Comment by piggz** [comment]
This is now fixed and will be in the next release
