### ISSUE TITLE
Can't pair on Desktop build (Fedora) due to qml error

### ISSUE THREAD

**Issue by theseer** [piggz/harbour-amazfish#240]
Roughly following the build instructions for Ubuntu on my Fedora 36 machine, I managed to get it to build after installing what seems to have been the Fedora equivalents of the Ubuntu packages listed.

I can start the UI and it allows me to create a profile (the birthday widget is broken and doesn't offer me a nice way to jump ahead on years..).

I can also select `pair with watch`, selecting my `Amazfit GTS 2` opens the tab to enter the Auth key. After pasting it in, pressing the `-> accept` button though, doesn't do anything anymore - but there's an error in the console:

```
theseer@nyda /usr/local/bin $ ./harbour-amazfish-ui 

QSocketNotifier: Can only be used with threads started with QThread
kf.kirigami: Failed to find a Kirigami platform plugin
qrc:/qml/pages/FirstPage.qml:79:13: QML LabelPL: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
qrc:/qml/pages/FirstPage.qml:90:13: QML BusyIndicatorSmallPL: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
qrc:/qml/components/platform/StackPL.qml:33:5: QML Connections: Cannot assign to non-existent property "onInfoActiveChanged"
qrc:/qml/components/platform/PagePL.qml:49: TypeError: Cannot read property 'title' of undefined
file:///usr/lib64/qt5/qml/org/kde/kirigami.2/ContextDrawer.qml:128:9: QML ListView: Binding loop detected for property "topMargin"
QQmlComponent: Component is not ready
file:///usr/lib64/qt5/qml/org/kde/kirigami.2/PageRow.qml:884: Error: Error while loading page: qrc:/qml/pages/PairPage.qml:66 Cannot assign to non-existent property "filters"
```

The last two lines repeat when pressing the `-> Accept` again.
I'm a bit lost ;)

**Comment by piggz** [comment]
Hi, yeah, someone else reported this too on a desktop ... i wonder if something changed in BluezQt ... can you get me the package version of that on your distro?

**Comment by theseer** [comment]
```console
theseer@nyda ~ $ rpm -qa |grep kf5-bluez-qt
kf5-bluez-qt-5.97.0-1.fc36.x86_64
```

Anything else I can do to support this?

**Comment by piggz** [comment]
Ok, i found the problem ...
I recently switched the code to bluezqt5 as the older code was deprecated.  however, it appears jolla has a patch to add the filter property which isnt upstream
https://github.com/sailfishos/kf5bluezqt/blob/master/rpm/0009-Add-filtering-options-to-DeclarativeDevicesModel.-Co.patch

**Comment by theseer** [comment]
Nice catch. Probably wouldn't have come up with that angle...

Anything I can do to help fix that? I'm not sure applying the same patch on Fedora would be a good idea? I technically could build my own package and include that patch of course...

**Comment by piggz** [comment]
Id prefer something that worked for everyone, id accept a PR which changes the behaviour if youre any good with qt/qml!

**Comment by theseer** [comment]
Not really. But that doesn't stop me from having a look :)

**Comment by piggz** [comment]
@theseer Could you try commenting out the line
filters: BluezQt.DevicesModelPrivate.AllDevices
as its probably not even required, i guess by default add devices are listed anyway?

**Comment by piggz** [comment]
Actually, maybe try something like
Component.onCompleted: {
        console.log("Manager operational:", _bluetoothManager.operational, _bluetoothManager.usableAdapter);
        if (devicesModel.filters) {
            filters = 0x03;
        }
    }

**Comment by piggz** [comment]
Ok, i committed something, can you see if it now works on desktop?

**Comment by theseer** [comment]
Yes! Works on my Desktop Fedora now.

Or, at least I get past the problem this issue was about.

After seemingly successfully pairing, I'm not stuck at exactly the same spot as described in https://github.com/piggz/harbour-amazfish/issues/231#issuecomment-1241635269.

But for this part, we can close this issue.
