### ISSUE TITLE
Call receive on Xperia 10 III (GTR2) ?

### ISSUE THREAD

**Issue by LKielland** [piggz/harbour-amazfish#245]
Hi,
I finally got this working yesterday and I'm kind of blown away by how well Amazfish is working. 
I do have a potential issue. I do not get a notification when I receive a call, so I cannot accept or reject from the watch. I do get a notification once a call has ended or is missed. Should I be able to do this? The watch has a built in microphone and speaker so it would be cool to be able to do it.

Also, there is no longer a "settings" menu item on the watch itself. Is that because it has been "replaced" by the 'device settings' within amazfish?

**Comment by debeliu** [comment]
Hi @LKielland,
I managed to make call working.
You have to go on settings on the watch and pair the phone from the watch.
This will create another Bluetooth connection for the call functionality.

To make settings reappear on the watch, I used zepp app on android, and made some changes to the menu to get the app to resend the "good" config with settings.

Pity however that settings disappears as soon as you reconnect with amazfish

**Comment by piggz** [comment]
In Amazfish, go to settings, device settings, Huami Display Items where you can enable and re-order the menu items on the watch.
