### ISSUE TITLE
Start service on boot / Save this Option doesn´t work 4.4.0.72

### ISSUE THREAD

**Issue by FingusDE** [piggz/harbour-amazfish#249]
With Sandboxing Disabled by:

```
[X-Sailjail]
Sandboxing=Disabled
```

"Start service on boot" doesn´t work. It still doesn´t save this Option after pressing the Save-Button in Application-Settings.
When restart App, the "start service on boot"-setting is unchecked again.

**Comment by alex000090** [comment]
There is same problem on Xperia 10 III
Amazfish: 2.1.2-1.5.2
Sailfiah OS: 4.5.0.18
