### ISSUE TITLE
Amazfit GTR 42mm Watchfaces are not regognized as valid.

### ISSUE THREAD

**Issue by FingusDE** [piggz/harbour-amazfish#250]
When trying to send a new Watchface to my Amazfit GTR 42mm, App complains the Binary-File isn´t compatible/valid.

[Amazfit GTR 42mm Watchfaces.zip](https://github.com/piggz/harbour-amazfish/files/9971104/Amazfit.GTR.42mm.Watchfaces.zip)

The normal Amazfit GTR has 47mm Diameter and a higher Display-Resolution as my smaller 42mm-Variant. 
The Watchfaces are not compatible to each other.

So it seems that this smaller 42mm-Variant is not prepared in the Code.

**Comment by SolAZDev** [comment]
I second this, this seems to be a problem for the GTR2 as well
