### ISSUE TITLE
Calender Entries are Blank (no text only Time) with SFOS-Update 4.5

### ISSUE THREAD

**Issue by FingusDE** [piggz/harbour-amazfish#256]
With updating to SailfishOS 4.5 on Tama Community-Port Amazfish only send blank Calender Entries to the Watch (Amazfit GTS).

**Comment by FingusDE** [comment]
Still there:
![Bildschirmfoto_20230222_001](https://user-images.githubusercontent.com/48802630/220564672-df06dd38-f9bb-4a25-8875-f9068e0c4f71.png)
![grafik](https://user-images.githubusercontent.com/48802630/220564045-1fe84af6-c0fd-428a-95d8-afd290673639.png)

**Comment by theseer** [comment]
I'm having the same problem on my GTS 2.

It appears also that the data transfer for the statistics is broken, as I don't have any history step count or other health data anymore. Not sure if that is related in anyway.

I'll try to debug this a bit maybe later today - maybe I can figure something out ;)

**Comment by theseer** [comment]
I spent some time over the last days looking into this, but didn't find an obvious culprit as of yet.

Looking at the journal log (`journalctl -f`) when using the debug "update calendar", I can see the data is complete with title when sending. So it's not a problem with the calendar itself.

I'll debug some more :)

**Comment by piggz** [comment]
This seems to work Ok on my GTR2

**Comment by theseer** [comment]
I didn't have much time yet to debug further but given nothing changed in terms of the application itself and the log shows the calendar data is at least received correctly, it must be something related to the OS.

@piggz: Are you using the official bluetooth stack or your patched version despite being on the latest OS version?

**Comment by theseer** [comment]
There goes my - currently - last idea :-/

**Comment by piggz** [comment]
Ive just created 2 test entries in my calender, and both appeared on the phone just fine, except that the time is missing the minutes, so ill certainly look at that.

**Comment by theseer** [comment]
So maybe that's a regression to my fix with the minutes in #253 ? Even though I don't see how..

**Comment by piggz** [comment]
Hang on, i may not have restarted my daemon.....

**Comment by piggz** [comment]
Ah ok, that interesting, since restarting the daemon with the fix in #253, i have the minutes but no text!

**Comment by piggz** [comment]
Ok, ive fixed it.  In addition to the off-by-one, removing the 0x00 on the line below fixes both the minutes, and the missing text.

**Comment by theseer** [comment]
I have an idea:

The change I suggested for #253 adds a byte to the output, pushing the following `\00` by one position. Maybe the additional `\00` is now superflous and the culprit, marking the string as emtpy (c-style string termination)?

**Comment by theseer** [comment]
Yeah, that :-)

**Comment by piggz** [comment]
Which is strange because that doesnt match GB

**Comment by piggz** [comment]
Which is strange because that doesnt match GB

**Comment by piggz** [comment]
Ah no, this is correct, as per https://codeberg.org/Freeyourgadget/Gadgetbridge/src/branch/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/huami/HuamiSupport.java#L1079
date 0x00 title 0x00

**Comment by theseer** [comment]
Make a new release? ;-)
