### ISSUE TITLE
Add Calories, device and app to tcx file

### ISSUE THREAD

**Issue by juanro49** [piggz/harbour-amazfish#257]
Hi!

It's possible to add calories, device and application to the tcx file to show it in sport services like Strava?

I have tried uploading the tcx generated by amazfish (with Amazfit Bip S) manually edited adding calories (with the value that amazfish shows in the activity detail), device and app, and Strava shows calories and device.
![imagen](https://user-images.githubusercontent.com/11600804/221431050-d48f000c-9195-4247-910e-49486d2a9c65.png)
![imagen](https://user-images.githubusercontent.com/11600804/221431094-83ef7c8a-cb02-4982-b915-def5ded7bcad.png)
![imagen](https://user-images.githubusercontent.com/11600804/221431171-3bd74c0e-9a70-43e1-9344-496f250c44fa.png)

**Comment by piggz** [comment]
I think this should be possible yes.
