### ISSUE TITLE
Sync time/date !working w/ Infinitime 1.12.0

### ISSUE THREAD

**Issue by futurl** [piggz/harbour-amazfish#260]
Just updated my Pinetime with the newest Infinitime 1.12.0.
Time and Date do not sync after reconnecting to Amazfish.

Thx to Avamander the issue could be located to Amazfish.
See below extract from todays PineTime chat on telegram. We did the testing with nrf connect via Android.

/Begin

Avamander
If you press read I think it gives you the current value, but
"00070101000000000000" should set 2000-01-01 if I've counted my bytes correct

futurl .
Its working. Sending above values as BYTE ARRAY resets to 00:00 01.01.1972

Avamander
Yeah then it's highly likely that Amazfish is sending too few bytes and those get ignored.

/End

**Comment by piggz** [comment]
Now fixed
