### ISSUE TITLE
Bangle.js 2 not displaying notifications with "Messages" app

### ISSUE THREAD

**Issue by AcouBass** [piggz/harbour-amazfish#264]
At first I wasn't sure if this would be an Amazfish issue or if something's going wrong with Messages itself however after doing some tinkering with the Web IDE I think there's something up with how Amazfish sends notifications to the watch that is for whatever reason incompatible with the Messages app.  

So to test this I've installed these apps on the watch:
https://github.com/espruino/BangleApps/tree/master/apps/android
https://github.com/espruino/BangleApps/tree/master/apps/messages
https://github.com/espruino/BangleApps/tree/master/apps/messagegui

If I install the "Android Integration" app then the other two are pulled in automatically. I also installed this one: 

https://github.com/espruino/BangleApps/tree/master/apps/messagesdebug

This gave me a logfile which I've attached, the first one in the list was sent from Web IDE (and worked correctly) however the others are sent from Amazfish. You can see the Amazfish notifications are coming through to the watch (but not displaying)
, but I'm wondering if they are formatted incorrectly causing the Messages app to not display them correctly. I also don't get any notifications from actual Sailfish apps, or Android apps running under AppSupport/Alien Dalvik.  

If I remove the "Messages GUI" app and replace it with, for example, this:  

https://github.com/espruino/BangleApps/tree/master/apps/messages_light

The notification popups do display correctly however nothing happens if they are clicked and they still don't appear in the "Messages" app list.  

if I remove all 3 of the apps and replace them with the "Gadgetbridge" app as well as the default Notifications module, then I can get the standard text notifications however again this misses out on some functionality such as having them appear in a list in the Messages app.  

https://github.com/espruino/BangleApps/tree/master/apps/gbridge
https://github.com/espruino/BangleApps/tree/master/apps/notify

Hope that all makes sense, if there's anything I can do to help debug let me know!

[messagesdebug.log](https://github.com/piggz/harbour-amazfish/files/11748877/messagesdebug.log)

**Comment by Tsht** [comment]
I tried it, it seems I can get every notification using messages_light (or messages overlay) but even then I can't have phone call notification (it only lights up the screen).
I don't need to remove Messages GUI, using messages_light (or messages overlay) allows me to see notifications.

**Comment by Tsht** [comment]
I checked the code on messagesui, it may be that this app wants a not empty "id" field, but amazfish won't populate this field. I will try as I forked the repository and managed to generate a rpm.

**Comment by Tsht** [comment]
I tried passing a "-1" as identifier, I can get the notifications with MessageUI working then. I will propose this PR if my previous one is accepted (as it's on the same file, else piggz would get a merge)
