### ISSUE TITLE
Update firmware via Zepp vs "Download File" via Amazfish

### ISSUE THREAD

**Issue by flossgeek** [piggz/harbour-amazfish#267]
Hello,
I'm confused about the firmware flashing process for the Amazfit GTR 2. The firmware files are hard to obtain and there isn't a lot of documentation on this topic. Technically I would expect that updating the watch via the Zepp app would have the same effect as flashing firmware files manually with Amazfish. However, on the newest version (6.4.1.1), functionalities like receiving calls and displaying the current temperature/humidity are still not working when connected to my SailfishOS phone. I assume this has to do with the firmware or could it be something else?

**Comment by piggz** [comment]
Weather should work fine on the GTR2 ... for call support, you have to pair you phone, from the watch, as-well as pairing the watch from Amazfish.  This is because the GTR2 acts as a BT headset, so call notifications come via that route.
