### ISSUE TITLE
Untransaltable strings

### ISSUE THREAD

**Issue by dikonov** [piggz/harbour-amazfish#33]
1. There are quite a lot of untranslatable strings still. 

- "Birthday" in User Settings, 
- "disconnected" in device connection dialog 
- "File type/version:", "Choose File", "None" in Download File
- all Debug screen items.
This is not a complete list because I cannot see all screens without the watch (which I do not have).

2. The button displaying the birthday date should be moved to the next line because it gets too long and does not fit the Jolla 1 screen.

3. I would like to ask what do the following two options actually do for the sake of translation accuracy:
"Alert on fitness goal" (What is the fitness goal? Number of steps made? Calories spent? Smth else?)
"Use HRM for Sleep detection" (Does it detect the fact of sleeping or phases of sleep?)

**Comment by piggz** [comment]
thanks for the feedback, its great for you to translate without having the watch!
alert on fitnes goal, is the watch vibrating when the step count is reached
use hrm for sleep detection, is the watch using the HRM for more accurate sleep detection, afaict, without this it will just use motion.

**Comment by dikonov** [comment]
Thanks for comment! I guessed right.

I shall probably get the watch for my grandfather for constant HR moniring, but I want it to be fully localized and fully functional with Sailfish before.

**Comment by piggz** [comment]
Great, i hope it goes well for him .... i also added support for setting russian language as that was added in the latest firmware.
