### ISSUE TITLE
Alarms not staying set

### ISSUE THREAD

**Issue by BreenAJ** [piggz/harbour-amazfish#339]
Can enable and save an alarm.  It shows as enabled but the watch never buzzes to wake you up in the morning.If you check the alarm setting later on during the night it doesn't show as being set. This used to work and only seems to have stopped since the January update.

**Comment by BreenAJ** [comment]
To add further to my initial post. 

The alarm does stay sey on the phone sometimes but the alarm is never sent to the watch.

**Comment by sigurg** [comment]
Setting / editing alarms broke in the last update (at least with my Amazfit Bip).
It seems that the page is closed before the updates are sent to the watch, since removing [this line](https://github.com/piggz/harbour-amazfish/blob/master/ui/qml/pages/Settings-alarms.qml#L60) fixes the issue.
