### ISSUE TITLE
pairing amazfit bip watch not working

### ISSUE THREAD

**Issue by denis-robel** [piggz/harbour-amazfish#383]
I can't pair my Amazfit Bip watch wit actual Amazfish under SFOS 4.0.6.13.

The watch will be detected but it will not pair.

I reset the watch yet andit does not work.

Here the console output:

`
[D] unknown:0 - "" QQuickGridLayoutBase::rearrange() QSizeF(1080, 100.8)
[D] unknown:0 - QQuickGridLayoutBase::geometryChanged QRectF(0,375 1080x100.8) QRectF(0,0 1080x100.8)
[D] unknown:0 - "" QQuickGridLayoutBase::rearrange() QSizeF(1080, 100.8)
[D] unknown:0 - QQuickGridLayoutBase::onItemVisibleChanged
[D] unknown:0 - QQuickGridLayoutBase::updateLayoutItems
[D] unknown:0 - QQuickGridLayoutBase::invalidate()
[D] unknown:0 - QQuickLayout::invalidate(), polish()
[D] unknown:0 - QQuickGridLayoutBase::updateLayoutItems LEAVING
[D] unknown:0 - "" QQuickGridLayoutBase::rearrange() QSizeF(1080, 140)
[D] onCompleted:55 - Manager operational: true DeclarativeAdapter(0x5ad7229430)
[D] onTriggered:47 - Delayed Manager operational: true DeclarativeAdapter(0x5ad7229430)
[D] unknown:0 - void DaemonInterface::pair(const QString&, QString) "Amazfit Bip Watch" "/org/bluez/hci0/dev_C4_27_51_69_C7_00"
[D] unknown:0 - void DaemonInterface::pair(const QString&, QString) "Amazfit Bip Watch

`

**Comment by jmlich** [comment]
The log from daemon would be nice `journalctl --user -u harbour-amazfish`

**Comment by denis-robel** [comment]
> The log from daemon would be nice `journalctl --user -u harbour-amazfish`

sorry, can't provide a log file because I've got paired it and I don't want to risk to lose my datas again ...

The repairing was extremly difficult. The Amazfit Bip is one of the most easy to handle device normally because there is no server auth and so on. 
So maybe you can mark this issue as closed.
