### ISSUE TITLE
User profile settings page is not translated in the new .ts files

### ISSUE THREAD

**Issue by dikonov** [piggz/harbour-amazfish#40]
I installed the new version of the app and discovered that the User profile settings page is English-only and there are no corresponding source strings in the .ts, although I remember translating them.

**Comment by piggz** [comment]
oh, maybe this commit https://github.com/piggz/harbour-amazfish/commit/8074dfbdf93056e52780ec8e91949e1013a45e8e#diff-5fdef959c2d5e9634caa30822a38b640

**Comment by dikonov** [comment]
Are you going to reverse it? If not, I might re-add the translated strings, but will they work with the new version?

**Comment by piggz** [comment]
I think this is resolved now?
