### ISSUE TITLE
pairing and reconnection with Amazfit Bip broken

### ISSUE THREAD

**Issue by Danfro** [piggz/harbour-amazfish#401]
Hi, I do have an Amazfit Bip [A1608, firmware: v1.1.6.48] and run Amazfish 2.4.0 app on my OP5T focal.

Pairing the watch works only after like 10 attempts. I didn't manage to find a pattern yet that works. The bluetooth icon does show up on the device when pairing. It also does say "connection lost". So I assume its not the basic connection that fails, but it somehow misses a final step.
I do
- pair device
- search for device
- tap on my device
- on main screen the B bluetooth icon shows and the watch icon with a spinner
Then it mostly brings the disconnected error message on my watch.
After many attempts it eventually asks me to confirm pairing on my watch, then it works.

Reconnecting after the connection was lost e.g. due to long distance, never works. I need to try to re-pair to get a connection done. The bluetooth icon in the indicator does not get filled, so I guess maybe the bluetooth service is not "accessed" or activated properly?
Pressing "connect with watch" does only bring up the endless spinner in the B icon. That even stays there after closing the app or rebooting the device.

If you require further information I am happy to provide them.

**Comment by norayr** [comment]
i also have bip and i mantain the package for maemo leste.

i think my bip also doesn't reconnect and i need to repair it.
i am usually using pebble classic, but decided to use bip a couple of days ago.
and i think again i experience what you experience. that was sort of 'normal' for me, at least it worked somehow.

i will continue testing and i hope to come up with more comprehensive information about it.

**Comment by Danfro** [comment]
@norayr thanks for your reply. Good to know its not just me having this issue. My device should be `Mili_chaohu` firmware. Today I saw the "automatically reconnect" option in bluetooth settings for my bip. I ticked that box, hopefully that will help (no disconnect yet to test).

**Comment by Danfro** [comment]
@norayr actually ticking that "automatically reconnect" box in bluetooth settings for the Bip seems to have fixed the problem. Now my bip does reconnect. I think adding a note to readme might be a good idea.

**Comment by norayr** [comment]
> @norayr actually ticking that "automatically reconnect" box in bluetooth settings for the Bip seems to have fixed the problem. Now my bip does reconnect. I think adding a note to readme might be a good idea.

sorry where is it? in the watch? yes i confirm, it does connect back to amazfish on sailfish on xperia xa2, but it does not connect back to amazfish on maemo on pinephone.

 $ dpkg -l | grep -i amaz
ii  harbour-amazfish                                    2.1.3-1+leste1+m7                  arm64        Companion application for Huami Devices (such as Amazfit Bip, Cor, MiBand2/3 and GTS and GTS) and the Pinetime Infinitime

sailfish amazfish version is 2.4.0-1.11.1.jolla.armv7hl

@piggz so you referenced this issue in a commit and commit states 

```
Depending on device and operating system if there are problems with pairing or reconnecting you may need to take one action.
Open the bluetooth settings on your phone and head for known devices. There enter the settings for the watch and enable "reconnect automatically" for it.
```

any idea how to do it in bluetoothctl? in maemo i have no option in bluetooth settings. i just can use bluetoothctl.

also the pairing on maemo is done via app. i understand that's the right way, no?

so maybe then it should be done from bluetoothctl instead?

**Comment by Danfro** [comment]
@norayr I did prepare the commit with the note added to readme to share
my findings. But I am afraid I have no idea if the same can be done via
bluetoothctl or not or how it can be done on other OS (I am running
Ubuntu Touch).

I did a quick search for automatic connection and found [this
post](https://unix.stackexchange.com/questions/334386/how-to-set-up-automatic-connection-of-bluetooth-headset)
Maybe something explained there works for you?

**Comment by jmlich** [comment]
In the ubuntu touch is the connect automatically checkbox sets device as trusted see https://gitlab.com/ubports/development/core/lomiri-system-settings/-/blob/main/plugins/bluetooth/DevicePage.qml?ref_type=heads#L139
E.g ArchWiki says :
> If using a device without a PIN, one may need to manually trust the device before it can reconnect successfully
This can be done via `bluetoothctl` using `trust <MAC>`

I think it might be necessary to implement own agent to make this working reliably. I have noticed that some bluetooth adapter disconnects randomly or refuses to reconnect and reboot of phone and/or smartwatch is necessary.
