### ISSUE TITLE
Unable to install chum on Sailfish

### ISSUE THREAD

**Issue by nshiell** [piggz/harbour-amazfish#408]
Running:
`[defaultuser@Xperia10III Download]$ devel-su pkcon install-local sailfishos-chum-repo-config-0.6.8-1.4.1.jolla.src.rpm
Password:
Installing files
Finished
Fatal error: File /home/defaultuser/android_storage/Download/sailfishos-chum-repo-config-0.6.8-1.4.1.jolla.src.rpm is not found or unsupported`

The file is in the Download directory
Sailfish OS 4.6.0.15
Product: Xperia 10 iii

What's not right, also trying to install the file with the file manager doesn't work either

**Comment by piggz** [comment]
To get the chum store installed, you are best to use this web app, which will download the correct gui application for you https://chumrpm.netlify.app/

**Comment by nshiell** [comment]
I confirm that I used the web app to download the files
The error above was after downloading the files from the web app

**Comment by piggz** [comment]
Ah, youre right ... the website is only serving the .src.rpm's and not the binaries ... will look into it..

**Comment by piggz** [comment]
For now, you can grab the rpm here https://build.sailfishos.org/package/binaries/sailfishos:chum/sailfishos-chum-gui?repository=4.6_aarch64

**Comment by nshiell** [comment]
In order to download the chum GUI thing, I followed this link chain:
https://build.sailfishos.org/package/binaries/sailfishos:chum/sailfishos-chum-gui?repository=4.6_aarch64
https://repo.sailfishos.org/obs/sailfishos:/chum/4.6_aarch64/
https://repo.sailfishos.org/obs/sailfishos:/chum/4.6_aarch64/aarch64/
https://repo.sailfishos.org/obs/sailfishos:/chum/4.6_aarch64/aarch64/sailfishos-chum-gui-0.6.8-1.9.1.jolla.aarch64.rpm

Now installed :)
