### ISSUE TITLE
Better Coverpage

### ISSUE THREAD

**Issue by sailfishmods** [piggz/harbour-amazfish#41]
Hey, could you change the cover page a bit? I think the BT address is something we do not need.
I once uploaded a picture, would not that make more sense? But do not laugh ^^

https://www2.pic-upload.de/img/35690194/coverpage2.png

**Comment by dikonov** [comment]
Are you going to reverse it? If not, I might re-add the translated strings, but will they work with the new version?

**Comment by sailfishmods** [comment]
the answer is probably wrong here :)

**Comment by dikonov** [comment]
Sorry...
