### ISSUE TITLE
Time synchronization Bangle.js 2

### ISSUE THREAD

**Issue by RonnyB74** [piggz/harbour-amazfish#421]
Unfortunately, I am not able to send the time from the phone to the Bangle.js 2. Is this not yet implemented?

**Comment by jmlich** [comment]
It seems, that it is not implemented.
It should send something like this
https://github.com/Freeyourgadget/Gadgetbridge/blob/f05043481ce85a80db3a8c93efbcc14f7d7da963/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/banglejs/BangleJSDeviceSupport.java#L1087

It case of PineTime it is implemented in initialize()
https://github.com/piggz/harbour-amazfish/blob/2963f7c7bde81b68ad11b3d86410c0ad84709191/daemon/src/devices/pinetimejfdevice.cpp#L204

So it should be added somewhere here:
https://github.com/piggz/harbour-amazfish/blob/2963f7c7bde81b68ad11b3d86410c0ad84709191/daemon/src/devices/banglejsdevice.cpp#L162

I can try to implement it without testing, I don't have device to test, but It may end up with some strange behaviour which needs debugging.
