### ISSUE TITLE
Amazfit COR Sending Second File...

### ISSUE THREAD

**Issue by marxistvegan** [piggz/harbour-amazfish#49]
Hey all,
Wondering if anyone has had this issue. I have  Sony Xperia X and yesterday I sent the Mili_chaohu.fw file over and I was expecting a moment to send the Mili_chaohu.res file after, but the process happened so quick that I think i missed the chance. What currently is happening is it is a black screen on the COR, bluetooth sees the COR but does not connect, Amazfish when searching to pair sees the device too but I am not able to connect the watch to send the final file. 
Any ideas on what i can do to get the Mili_chaohu.res file over?

**Comment by piggz** [comment]
well, its a brave soul who attempts  a firmware upgrade on an unsupported device, i think you may have sent the wrong files! the cor will use a different firmware so i hope you havnt bricked it!

you could attempt a repair on an android device using the official app maybe?

i would be reluictant to add firmware detection for cor files without testing it.

**Comment by marxistvegan** [comment]
Ok will check with my roommate if I can use their android device and see what I can do. In the event that I get it going, what testing could I do? I thought i read a comment in openrepos or one here that someone succeeded with COR.

**Comment by piggz** [comment]
im not aware of anyone flashing a fw to a cor, just using the app generally.  the mii_chouou files are bip specific, if you look in the mifit apk, there is a json file which identifies the corret files for each device.

**Comment by piggz** [comment]
there is also gadget bridge which would give you more control over the flashing process, once you have the correct files

**Comment by marxistvegan** [comment]
I was looking at the firmware.json file, but not sure how to interpret which would be the cor, they have other names instead.

**Comment by marxistvegan** [comment]
So I ended up getting another and Amazfish does work with the Cor right out of the box with out any need to upload/update the firmware.

**Comment by marxistvegan** [comment]
I am going to close this since it was my error, I am waiting until the battery dies on the original if it works I might consider returning it or finding a local buyer.

**Comment by piggz** [comment]
you could open an issue to say that it shouldnt offer to send firmwares to incompatible devices, i should be able to do that. what did your cor do with the mifit app?can it pair? is it visible on BT?

**Comment by piggz** [comment]
if you get to the point of throwing the cor in the bin how would you feel about sending me it, and i cuuld try and see whats going on? would depend if its worth it, im in the UK.

**Comment by marxistvegan** [comment]
> if you get to the point of throwing the cor in the bin how would you feel about sending me it, and i cuuld try and see whats going on? would depend if its worth it, im in the UK.

Might be possible, but I would not mind getting my money back on it or part of it. We will see giving it another few days until i try it again

**Comment by piggz** [comment]
no problem. you can use tools on linux to see what BLE services are being advertised, that may give an idea as to how much of it is functionioning.  there is also a android BLE scanning tool but i forgot its name.

**Comment by marxistvegan** [comment]
> no problem. you can use tools on linux to see what BLE services are being advertised, that may give an idea as to how much of it is functionioning. there is also a android BLE scanning tool but i forgot its name.

Linux side I would like more info on in terms of testing. As for android I lack a device outside of asking a roommate, which is what I did with trying the mifit app. Otherwise just SailfishOS all the way :)

**Comment by piggz** [comment]
https://www.jaredwolff.com/get-started-with-bluetooth-low-energy/
