### ISSUE TITLE
Amazfit Cor settings

### ISSUE THREAD

**Issue by marxistvegan** [piggz/harbour-amazfish#50]
Hey all, 
So very new to this but I have the Amazfit Cor running the 1.0.6.65 firmware and I am able to download activity to my Amazfish, but there are two things I am trying to figure out one is the settings, unfortunately I live in the US so we use the imperial settings. However when I try to save that it defaults back to metric. The other settings like Date and Time when changed stay saved. The other feature is characters involved in the weather settings. I live in Boston, which I can search and save and see that the weather is accurate however the letters or characters for the Location are boxes with question marks in them. 

Also what other way can I get the logs, when I use the Debug Info and select Fetch debug log it continuously shows a circle rotating and does not appear to get the logs.

**Comment by piggz** [comment]
if you run amazfish from the commandline you might get some useful info.  As I dont have a Cor (and officially only support the Bip) its hard to tell why the logs dont download, but the program output may help.

In my next version, I am making it easier to support additional devices, but will need devs to add support for those devices.

**Comment by piggz** [comment]
Is this still an issue?

**Comment by marxistvegan** [comment]
No longer have the device in question.
