### ISSUE TITLE
[Feature Request] Prevent sending the incorrect firmware to incompatible devices

### ISSUE THREAD

**Issue by marxistvegan** [piggz/harbour-amazfish#51]
Suggestion coming from issue #49 

There are specific firmware for specific devices, the idea here is to use the hardware ID and prevent sending the incompatible firmware. i.e. when sending file to Amazfit Cor it should reject any Mili_chaohu.* files and only accept Mili_tempo.* files.

**Comment by BonoNL** [comment]
Is there a list of which files should match with each model?

**Comment by piggz** [comment]
This is now implemented in 1.1.0 Firmwares are checked against the reported device name.
