### ISSUE TITLE
Sports Activity Sync problems with Bip fw 1.1.5.04

### ISSUE THREAD

**Issue by rsw909** [piggz/harbour-amazfish#52]
Since upgrading the bip to fw 1.1.5.04 all sports activities sync in the same broken way. When the GPX is viewed, the track heads due North for a series of points, with the time not advancing, Then East for a series of points with time not advancing. There are then another series of points at fixed time before the usual pattern of one point per second begins. Once the "one per second" section begins, the trail has the correct shape of the route tracked, but it is offset to the North and East of the real location by the distance moved in the first two blocks where time did not advance.

misbehaviour happens on all exercise types, and not when syncing to the MiFit app on IOS, which combined with repeatability suggests it's not just a GPS glitch.

example gpx file attached. I can share more if required
[Biking-20181122-1954.zip](https://github.com/piggz/harbour-amazfish/files/2610076/Biking-20181122-1954.zip)

Thanks for the great work on this app so far.

**Comment by piggz** [comment]
Thanks for the report. Thankfully the same bug is reported in gadget bridge with the latest firmware, and they claim to have fixed it, so i should be able to go through their commits to see what h the issue was

**Comment by piggz** [comment]
Fix looks easy!

**Comment by piggz** [comment]
Please test with new release 0.8.0

**Comment by rsw909** [comment]
working a treat again. Thanks for your work
