### ISSUE TITLE
[feature request] Periodically data sync

### ISSUE THREAD

**Issue by je-nix** [piggz/harbour-amazfish#55]
It would be great if there was a possibility to sync data (health data and / or sports activities) periodically. From my commute to work, there are usually 2 sports activities present, so I would like to let Amazfish sync them automatically (say at 09:00 and 20:00).
I imagine either an option in the settings "Sync health data every X hours" / "Sync activities every X hours" or command parameters (like `harbour-amazfish --sync-data --sync-acitvities`) that can be used with cron. Ideally, Amazfish would then query data sets from the watch until all stored data was transferred ("No data to transfer").

Is this possible to implement?
Thanks for taking a look at it.

**Comment by piggz** [comment]
Fixed some time ago
