### ISSUE TITLE
[Device] Support for Mi Band 3

### ISSUE THREAD

**Issue by marvinborner** [piggz/harbour-amazfish#56]
Hey, as I own a Mi Band 3 and it's pretty much the same firmware I wanted to try if amazfish is compatible with the Mi Band 3 too.  That's why I've edited the `PairPage.qml` file and changed its corresponding line to "Mi Band 3" - no problem so far. But when I try to build it (Sailfish OS IDE - qt creator) the console tells me that there are some missing build dependencies (`kcoreaddons-devel` and `kdb-devel`). Both of these libraries are already installed on my phone but I don't actually know how to fix this or whether I have to install these on my PC itself (Arch Linux) - which I actually wouldn't think of. It would be fantastic if you'll either provide some build instructions, make the sources of your devel dependencies public or compile a version yourself, implementing the support for the Mi Band 3. I know this isn't a normal issue or something, but these errors have driven me crazy and I just want to add support for more devices.
Thanks in advance.

**Comment by piggz** [comment]
All the deps are on openrepos.  If you add my openrepos repo to the SDK buildroot, you should be able to build in the SDK.

The sources are structured to support more device types, just need devs with devices to add support for them! (subclass AbstractDevice etc...)

**Comment by piggz** [comment]
If you browse the code for GadgetBridge, you will find there any differences in the pairing protocol and supported services.

**Comment by piggz** [comment]
Basic support now available
