### ISSUE TITLE
Supported Firmware

### ISSUE THREAD

**Issue by Thaodan** [piggz/harbour-amazfish#6]
Which firmware do you support?
My watch came with 0.0.9.29 and didn't paired.

**Comment by piggz** [comment]
Im on 0.1.1.39

I recommend upgrading using the official MiFit android app and try again.

Also, what phone do you have?  Some just dont support BLE so wont work at all.

**Comment by Thaodan** [comment]
```
[D] unknown:0 - BluezAdapter::BluezAdapter
[D] unknown:0 - Registered notifications listener for device
[D] unknown:0 - BluezAdapter::setAdapterPath: "/org/bluez/hci0"
[D] unknown:0 - VoiceCallsChanged
[D] unknown:0 - ActiveVoiceCallChanged
[D] unknown:0 - BluezAdapter::BluezAdapter
[D] unknown:0 - Using Wayland-EGL
[D] unknown:0 - Defaulting to webview scaling factor of 1.0
[D] onCompleted:12 - Application started
[D] unknown:0 - BluezAdapter::startDiscovery
[D] unknown:0 - BluezAdapter::setAdapterPath: "/org/bluez/hci0"
[D] unknown:0 - BluezAdapter::StartDiscovery: ""
[D] unknown:0 - BluezAdapter::stopDiscovery
[D] unknown:0 - BluezAdapter::StopDiscovery: ""
[D] unknown:0 - BluezAdapter::matchDevice:looking for: "Amazfit Bip"
[D] unknown:0 - Found: QVariant(QString, "Odin")
[D] unknown:0 - Found: QVariant(QString, "h.ear (MDR-EX750BT)")
[D] unknown:0 - Found: QVariant(QString, "FAOLAN")
[D] unknown:0 - Found: QVariant(Invalid)
[D] unknown:0 - Found: QVariant(Invalid)
[D] unknown:0 - Found: QVariant(QString, "KD-55XD7005")
[D] unknown:0 - Found: QVariant(QString, "VW BT 8671")
[D] unknown:0 - Found: QVariant(QString, "Amazfit Bip Watch")
[D] unknown:0 - BipInterface::pair: "/org/bluez/hci0/dev_FB_D9_DC_58_37_6E"
[D] unknown:0 - QBLEDevice::setDevicePath
[D] unknown:0 - true
[D] unknown:0 - BipDevice::pair
[D] unknown:0 - BipDevice::disconnectFromDevice
[D] unknown:0 - QBLEDevice::disconnectFromDevice
[D] expression for onConnectionStateChanged:35 - pairing
[D] expression for onConnectionStateChanged:35 - pairing
[D] unknown:0 - QBLEDevice::pair
```
 log during pairing.

**Comment by piggz** [comment]
Ok, unpair it from the BT settings page and try that, and supply the logs.

I'll be posting a new version shortly, but i dont think ive made any pairing changes.

**Comment by piggz** [comment]
New version posted

**Comment by Thaodan** [comment]
Thats the output so far:
``[nemo@Sailfish ~]$ harbour-amazfish 
[D] unknown:0 - BluezAdapter::BluezAdapter
[D] unknown:0 - Registered notifications listener for device
[D] unknown:0 - BluezAdapter::setAdapterPath: "/org/bluez/hci0"
[D] unknown:0 - VoiceCallsChanged
[D] unknown:0 - ActiveVoiceCallChanged
[D] unknown:0 - BluezAdapter::BluezAdapter
[D] unknown:0 - Using Wayland-EGL
[D] unknown:0 - Defaulting to webview scaling factor of 1.0
[D] onCompleted:12 - Application started
[D] unknown:0 - BluezAdapter::startDiscovery
[D] unknown:0 - BluezAdapter::setAdapterPath: "/org/bluez/hci0"
[D] unknown:0 - BluezAdapter::StartDiscovery: ""
[D] unknown:0 - BluezAdapter::stopDiscovery
[D] unknown:0 - BluezAdapter::StopDiscovery: ""
[D] unknown:0 - BluezAdapter::matchDevice:looking for: "Amazfit Bip"
[D] unknown:0 - Found: QVariant(QString, "Odin")
[D] unknown:0 - Found: QVariant(QString, "h.ear (MDR-EX750BT)")
[D] unknown:0 - Found: QVariant(QString, "FAOLAN")
[D] unknown:0 - Found: QVariant(Invalid)
[D] unknown:0 - Found: QVariant(Invalid)
[D] unknown:0 - Found: QVariant(QString, "KD-55XD7005")
[D] unknown:0 - Found: QVariant(QString, "VW BT 8671")
[D] unknown:0 - Found: QVariant(QString, "Amazfit Bip Watch")
[D] unknown:0 - BipInterface::pair: "/org/bluez/hci0/dev_C5_BB_5E_00_C7_88"
[D] unknown:0 - QBLEDevice::setDevicePath
[D] unknown:0 - true
[D] unknown:0 - BipDevice::pair
[D] unknown:0 - BipDevice::disconnectFromDevice
[D] unknown:0 - QBLEDevice::disconnectFromDevice
[D] expression for onConnectionStateChanged:35 - pairing
[D] expression for onConnectionStateChanged:35 - pairing
[D] unknown:0 - QBLEDevice::pair
``
Whats weard is that the watch never asks for confirmation of the connection.

**Comment by piggz** [comment]
ok ... i can reproduce ... i just did a factory reset and it doesnt pair....

**Comment by Thaodan** [comment]
thats great to hear that I dont cause the issue.
I read on openrepos that someone had the issue too.

**Comment by Thaodan** [comment]
Have you an idea why?

**Comment by piggz** [comment]
0.4.6 is on open repos and works for me from a factory reset device

**Comment by Thaodan** [comment]
So fitness tracking was broken?

**Comment by piggz** [comment]
Well, fitness tracking isnt even implemented yet!

**Comment by Thaodan** [comment]
so what caused the issue?

How long should pairing take?

**Comment by Thaodan** [comment]
I've waited about 5min and still no notification on the watch:
shell output:
[D] unknown:0 - BluezAdapter::BluezAdapter
[D] unknown:0 - Registered notifications listener for device
[D] unknown:0 - BluezAdapter::setAdapterPath: "/org/bluez/hci0"
[D] unknown:0 - VoiceCallsChanged
[D] unknown:0 - ActiveVoiceCallChanged
[D] unknown:0 - BluezAdapter::BluezAdapter
[D] unknown:0 - Using Wayland-EGL
[D] unknown:0 - Defaulting to webview scaling factor of 1.0
[D] onCompleted:14 - Application started
[D] unknown:0 - BluezAdapter::startDiscovery
[D] unknown:0 - BluezAdapter::setAdapterPath: "/org/bluez/hci0"
[D] unknown:0 - BluezAdapter::StartDiscovery: ""
[D] unknown:0 - BluezAdapter::stopDiscovery
[D] unknown:0 - BluezAdapter::StopDiscovery: ""
[D] unknown:0 - BluezAdapter::matchDevice:looking for: "Amazfit Bip"
[D] unknown:0 - Found: QVariant(QString, "Odin")
[D] unknown:0 - Found: QVariant(QString, "h.ear (MDR-EX750BT)")
[D] unknown:0 - Found: QVariant(QString, "FAOLAN")
[D] unknown:0 - Found: QVariant(Invalid)
[D] unknown:0 - Found: QVariant(Invalid)
[D] unknown:0 - Found: QVariant(QString, "KD-55XD7005")
[D] unknown:0 - Found: QVariant(QString, "VW BT 8671")
[D] unknown:0 - Found: QVariant(QString, "Amazfit Bip Watch")
[D] unknown:0 - BipInterface::pair: "/org/bluez/hci0/dev_C5_BB_5E_00_C7_88"
[D] unknown:0 - QBLEDevice::setDevicePath
[D] unknown:0 - true
[D] unknown:0 - BipDevice::pair
[D] unknown:0 - BipDevice::disconnectFromDevice
[D] unknown:0 - QBLEDevice::disconnectFromDevice
[D] expression for onConnectionStateChanged:35 - pairing
[D] expression for onConnectionStateChanged:35 - pairing
[D] unknown:0 - QBLEDevice::pair

firmware 0.1.1.36

**Comment by Thaodan** [comment]
My what is this:
https://tradingshenzhen.com/en/gadgets/996-xiaomi-amazfit-watchlite.html

**Comment by piggz** [comment]
Hmm, i'll do some more testing ... but you should be ok.
Try a factory reset on the watch and delete any pairing and reboot the phone to make sure.
After the ::pair message,you should get
Paired!
then a disconnect and connect

**Comment by Thaodan** [comment]
D] unknown:0 - BluezAdapter::matchDevice:looking for: "Amazfit Bip"
[D] unknown:0 - Found: QVariant(QString, "Odin")
[D] unknown:0 - Found: QVariant(QString, "FAOLAN")
[D] unknown:0 - Found: QVariant(Invalid)
[D] unknown:0 - Found: QVariant(Invalid)
[D] unknown:0 - Found: QVariant(QString, "KD-55XD7005")
[D] unknown:0 - Found: QVariant(QString, "VW BT 8671")
[D] unknown:0 - Found: QVariant(QString, "Amazfit Bip Watch")
[D] unknown:0 - BipInterface::pair: "/org/bluez/hci0/dev_C5_BB_5E_00_C7_88"
[D] unknown:0 - QBLEDevice::setDevicePath
[D] unknown:0 - true
[D] unknown:0 - BipDevice::pair
[D] unknown:0 - BipDevice::disconnectFromDevice
[D] unknown:0 - QBLEDevice::disconnectFromDevice
[D] expression for onConnectionStateChanged:35 - pairing
[D] expression for onConnectionStateChanged:35 - pairing
[D] unknown:0 - QBLEDevice::pair


I did that (as far as I can read chinese :d).
No success.

**Comment by piggz** [comment]
Out of interest, if after failing to pair, if you switch to the debug page, what is the Connection State?

Also, if you open the BT settings page on sfos, what is the state of the watch? is it in the paired group? is it connected?

If it is paired, and you click on the watch to connect, and switch back to amazfish, does anything happen?

**Comment by Thaodan** [comment]
Pairing and connecting  works with  0.3.x
 Ps: pairing  looks much better there,  not so verbose as with  4.

**Comment by Thaodan** [comment]
Should the connection stay valid after upgrading?
I get : 
`[D] unknown:0 - BipInterface::connectToDevice: "E3:22:DC:67:59:E8"
[D] unknown:0 - BipInterface::connectToDevice:device was not valid
`
When starting the app.

**Comment by Thaodan** [comment]
Here is a log from pairing with 0.3.x
```
[D] unknown:0 - Created bip pairer
[D] unknown:0 - Registered notifications listener for device
[D] unknown:0 - VoiceCallsChanged
[D] unknown:0 - ActiveVoiceCallChanged
[D] unknown:0 - Using Wayland-EGL
[D] unknown:0 - Defaulting to webview scaling factor of 1.0
[D] expression for onConnectionStateChanged:35 - connecting
[D] onCompleted:12 - Application started
[D] unknown:0 - Disconnecting from device
[D] unknown:0 - LowEnergy controller disconnected
[D] expression for onConnectionStateChanged:35 - disconnected
[D] unknown:0 - Found "00:09:DD:50:86:D5" "Odin"
[D] unknown:0 - Found "68:D9:3C:93:B5:39" "68-D9-3C-93-B5-39"
[D] unknown:0 - Low Energy device found. Scanning more...
[D] unknown:0 - Found "88:C6:26:C2:B1:EB" "88-C6-26-C2-B1-EB"
[D] unknown:0 - Low Energy device found. Scanning more...
[D] unknown:0 - Found "90:CD:B6:28:22:CC" "KD-55XD7005"
[D] unknown:0 - Found "AC:7A:4D:9A:2A:E9" "VW BT 8671"
[D] unknown:0 - Found "D2:56:8F:33:80:C9" "Amazfit Bip Watch"
[D] unknown:0 - Low Energy device found. Scanning more...
[D] unknown:0 - Found amazfit
[D] unknown:0 - Found "D8:9C:F7:27:87:04" "Amazfit Bip Watch"
[D] unknown:0 - Low Energy device found. Scanning more...
[D] unknown:0 - Found amazfit
[D] unknown:0 - Service discovered: "{00001800-0000-1000-8000-00805f9b34fb}"
[D] unknown:0 - Service discovered: "{00001801-0000-1000-8000-00805f9b34fb}"
[D] unknown:0 - Service discovered: "{0000180a-0000-1000-8000-00805f9b34fb}"
[D] unknown:0 - Service discovered: "{00001530-0000-3512-2118-0009af100700}"
[D] unknown:0 - Service discovered: "{0000fee0-0000-1000-8000-00805f9b34fb}"
[D] unknown:0 - Service discovered: "{0000fee1-0000-1000-8000-00805f9b34fb}"
[D] unknown:0 - Creating service object
[D] unknown:0 - "Unknown Service"
[D] unknown:0 - Discovering services...
[D] unknown:0 - Service discovered: "{0000180d-0000-1000-8000-00805f9b34fb}"
[D] unknown:0 - Service discovered: "{00001811-0000-1000-8000-00805f9b34fb}"
[D] unknown:0 - Service discovered: "{00001802-0000-1000-8000-00805f9b34fb}"
[D] unknown:0 - Service discovered: "{00003802-0000-1000-8000-00805f9b34fb}"
[D] unknown:0 - Service scan done.
[D] unknown:0 - Service discovered.
[D] unknown:0 - Characteristic: "{00000009-0000-3512-2118-0009af100700}" ""
[D] unknown:0 - Characteristic: "{0000fedd-0000-1000-8000-00805f9b34fb}" ""
[D] unknown:0 - Characteristic: "{0000fede-0000-1000-8000-00805f9b34fb}" ""
[D] unknown:0 - Characteristic: "{0000fedf-0000-1000-8000-00805f9b34fb}" ""
[D] unknown:0 - Characteristic: "{0000fed0-0000-1000-8000-00805f9b34fb}" ""
[D] unknown:0 - Characteristic: "{0000fed1-0000-1000-8000-00805f9b34fb}" ""
[D] unknown:0 - Characteristic: "{0000fed2-0000-1000-8000-00805f9b34fb}" ""
[D] unknown:0 - Characteristic: "{0000fed3-0000-1000-8000-00805f9b34fb}" ""
[D] unknown:0 - Getting the auth characteristic
[D] unknown:0 - Registering for notifications on the auth service
[D] unknown:0 - Writing special value to trigger pair dialog
[D] unknown:0 - Received data: 3 "100101"
[D] unknown:0 - Received initial auth success, requesting random auth number
[D] unknown:0 - Received data: 19 "100201bf7098fdc902123f3374ec61fdc62663"
[D] unknown:0 - Received random auth number, sending encrypted auth number
[D] unknown:0 - Received data: 3 "100301"
[D] expression for onPairComplete:54 - Paired with Amazfit Bip Watch D8:9C:F7:27:87:04
[D] unknown:0 - LowEnergy controller disconnected
[D] expression for onConnectionStateChanged:35 - connecting
[D] unknown:0 - Alert: "Somebody" "Title" "Hello from SailfishOS.  This is a long message sent over BLE
```!"

**Comment by piggz** [comment]
The 0.3 code is completely different from 0.4.  0.4 uses the bluez dbus api, with a wrapper i wrone myself, see https://together.jolla.com/question/183722/ble-gattgap-server-in-bluez5-not-working-as-expected/ for the reasons, but its a good bet that I wont switch back to the old way.

Here is a thought.  Im just using plain bluez......

Pair the watch in the sailfish settings app.  Does that work?  For me, it would sometimes come up that the pairing failed, and I either had to reset the watch or the phone until it worked.  Once that works, delete the pairing and try in the app.

If nothing happens after it says connected/pairing, switch back to the BT settings page and confirm if it is paired or not.

I did have some of these issues, but it did eventually pair, sometimes I had to try twice in the app.

**Comment by piggz** [comment]
regarding the device addres after upgrading, i swtich to a different scheme for storing the details, thats why the error message appears between 0.3 and 0.4.

To clear the settings
dconf reset "/uk/co/piggz/amazfish/pairedName" 
dconf reset "/uk/co/piggz/amazfish/pairedAddress"

**Comment by Thaodan** [comment]
Pairing worked after pairing the phone with the system settings after the application says its paired.
I think it would be great to use the system connection in the first place or that the app creates a system connection.

**Comment by piggz** [comment]
It actually does use the same method as the system dialog.  What I think will help, is adding a 'try again' button within the app.  I have already added support for getting the status back from the pair attempt .... the only problem Im having is testing it, as it always works first time for me!  I may release something anyway for feedback, but im also working on getting back the activity data, and want that in the next version.

**Comment by Thaodan** [comment]
Did you push these changes to github? If yes I can test and report.

**Comment by piggz** [comment]
Can this now be closed?  Plenty of working report on openrepos.
