### ISSUE TITLE
Size of GPX field in kexi DB to low

### ISSUE THREAD

**Issue by je-nix** [piggz/harbour-amazfish#61]
The field containing the GPX data in the sport activity table of the kexi database seems to be limited to 31980 chars. For cycling activities, this relates to approximately 5 Minutes of data.
Is there a possibility to increase the field?

Thanks.

**Comment by piggz** [comment]
ill take a look...on a side note, the gpx files are stored individually too.  if laufhelden is found, they will be stored there, otherwise somewhere in the homedir, cachelocation /logs/

**Comment by je-nix** [comment]
Thanks for the reply. Maybe you could add an option to specify where to store the gpx files if that is possible? Since the entry in the database is incomplete anyway, it could be replaced with the path and filename to the complete file.

**Comment by je-nix** [comment]
After not having found any .gpx files on my phone for previous activities, I took a quick look into your code. I presume the default location "QStandardPaths::CacheLocation" in src/operations/sportsdetailoperation.cpp refers to /home/nemo/.cache or /home/nemo/.cache/harbour-amazfit, though the second one does not exist and there is no 'logs' folder in .cache on my phone.
I'm no SFOS developer nor experienced with C++ / QT but from my quick understanding of the referenced introductions [0]&[1] it may be better to use "QStandardPaths::DataLocation" to store the .gpx files, as the system may clean up files inside the cache directory at any times, especially if the storage is low. Of course, it would be even better to include an option to the settings to specify whether or not the .gpx should be saved and if so, in which folder. But this is probably a bigger task to implement.

Do you think you can include this change in the next release if it sounds feasible to you? I also offer to test these changes beforehand if you want (and can provide me with a test build).

[0]: https://harbour.jolla.com/faq
[1]: https://sailfishos.org/develop/docs/libsailfishapp/

**Comment by piggz** [comment]
Changed location in 0.8.8
