### ISSUE TITLE
Refreshed app icon

### ISSUE THREAD

**Issue by JSEHV** [piggz/harbour-amazfish#63]
Suggested refreshed app icon:

![harbour-amazfish-172x172](https://user-images.githubusercontent.com/5128988/55651383-b3146c00-57e8-11e9-8e26-49efb78e6322.png)

Original .svg file:

[harbour-amazfish.zip](https://github.com/piggz/harbour-amazfish/files/3049342/harbour-amazfish.zip)

**Comment by piggz** [comment]
Gonna keep with the current clock-based icon for now as i think its more relevant.  Cheers.
