### ISSUE TITLE
Custom action (run .sh script) on (double) button press

### ISSUE THREAD

**Issue by j1warren** [piggz/harbour-amazfish#65]
Hi, piggz.
Such functionality exists on several android apps, is it possible to implement it on amazfish?

PS Thanks for the app! Never knew it would be possible to use up-to-date smart-watch with SFOS.

**Comment by norayr** [comment]
i second this. what i miss (in particularly) from pebble functionality is ability to navigate through music tracks, back and forth. you don't want to get the phone from the pocket to switch to the next track while running.

**Comment by je-nix** [comment]
My wish list for Amazfish includes a similar item: Make the double press action (which currently is "next track") configurable, at least with an option to turn it off.
I miss the option to navigate through the tracks from my Pebble as well. However, the current setup is not satisfying for me, so I rarely use it. But whenever I'm wearing gloves for biking they often accidentally perform double clicks, skipping through my playlist and resuming playback (and thus increase battery consumption).

It would be even better if there was an option for custom commands (e.g. execute a script which then can perform actions based on the twist of the pin or even input gestures on the watch). But I take it this is not easily implemented.

**Comment by piggz** [comment]
I have some code ready fro this and am after testers...

**Comment by piggz** [comment]
This is now implemented, and a test build is available from https://build.merproject.org/package/show/home:piggz:harbour-amazfish-dev/harbour-amazfish
You need to go to settings, app, button actions, and assign actions.
custom runs ~/harbour-amazfish-script.sh, passing in the number of presses, so you can do 3 separate actions

**Comment by norayr** [comment]
omg thank you!
