### ISSUE TITLE
Can't pair to right Amazfit device

### ISSUE THREAD

**Issue by Jojonintendo** [piggz/harbour-amazfish#66]
Good afternoon,

I have just installed the app on my Xperia XA2 (with latest Sailfish X Beta), but I can't seem to get my Amazfit Bip to pair with it. I can pair it via the system, which shows that the watch is connected, but then I noticed that Amazfish always tries to pair with a different MAC address.

In the bluetooth list of devices, there is another one named "Amazfit", different from my "Amazfit Bip Watch", and I am pretty sure that Amazfish is trying to pair with it instead of the watch.

What are my options? I have already tried to get to a different place, but the wrong device is always listed in the bluetooth list, so the app will continuously try to connect to it. Is there a way to remove it from the list, or try to select the right one from Amazfish?

Thank you very much for your work and time, this is definitely great to be able to use a smartwatch with Sailfish!

Jonas

**Comment by Jojonintendo** [comment]
Good morning,

I have been able to get some logs from the application:

```
[nemo@Sailfish ~]$ harbour-amazfish 
[D] unknown:0 - BluezAdapter::BluezAdapter
[D] unknown:0 - Registered notifications listener for device
[D] unknown:0 - DeviceFactory::createDevice: requested device of type: ""
[D] unknown:0 - DeviceFactory::createDevice: no suitable devices found, creating a Bip device as default
[D] unknown:0 - BluezAdapter::setAdapterPath: "/org/bluez/hci0"
[D] unknown:0 - DRIVERS:  ("org.kde.kdb.sqlite")
[D] unknown:0 - KDbConnection object created.
[D] unknown:0 - KDbConnection::connect() OK.
[D] unknown:0 - ("mi_band_activity", "sports_data")
[D] unknown:0 - VoiceCallsChanged
[D] unknown:0 - ActiveVoiceCallChanged
[D] unknown:0 - BluezAdapter::BluezAdapter
[D] unknown:0 - Using Wayland-EGL
[D] unknown:0 - "SELECT date(timestamp_dt), sum(steps) FROM mi_band_activity WHERE date(timestamp_dt) >= date('2019-04-04T00:00:00','-10 day') AND timestamp_dt <= '2019-04-04T23:59:59' GROUP BY date(timestamp_dt) ORDER BY timestamp_dt ASC"
[D] onCompleted:23 - Application started
[D] unknown:0 - BluezAdapter::startDiscovery
[D] unknown:0 - BluezAdapter::setAdapterPath: "/org/bluez/hci0"
[D] unknown:0 - BluezAdapter::StartDiscovery: ""
[D] unknown:0 - BluezAdapter::stopDiscovery
[D] unknown:0 - BluezAdapter::StopDiscovery: ""
[D] unknown:0 - BluezAdapter::matchDevice:**looking for: "Amazfit"**
[D] unknown:0 - Found: QVariant(QString, "arch-pc")
[D] unknown:0 - Found: QVariant(Invalid)
[D] unknown:0 - Found: QVariant(QString, "Amazfit")
[D] unknown:0 - BluezAdapter::deviceName:**looking for: "/org/bluez/hci0/dev_wrong_MAC_address**"
[D] unknown:0 - BipInterface::pair: "Amazfit" "**/org/bluez/hci0/dev_wrong_MAC_address**"
[D] unknown:0 - DeviceFactory::createDevice: requested device of type: "Amazfit"
[D] unknown:0 - DeviceFactory::createDevice: no suitable devices found, creating a Bip device as default
[D] unknown:0 - QBLEDevice::setDevicePath
[D] unknown:0 - true
[D] unknown:0 - AbstractDevice::pair
[D] expression for onConnectionStateChanged:39 - pairing
[D] expression for onConnectionStateChanged:39 - pairing
[D] unknown:0 - QBLEDevice::pair
[D] pair:102 - 
[D] onTriggered:115 - tmrWeatherRefresh 0
```

I have highlighted what I believe the problem is. The application is looking for a device called "Amazfish", when my watch is "Amazfish Bip Watch", and the MAC address it tries to connect to is not the one that belongs to the watch. Another weird thing is that I can't seem to find a way to make the entry "Amazfish" go away from the Bluetooth settings of the phone, even when all other entries are gone, this one never disappears. It sounds like the application detected the device the first time it ran, and now it is stuck forever on this one, even after reinstalling it.

I would really appreciate if someone could help me understand a little more what is happening, I am not afraid to tinker (that's why we love Sailfish :D).

Thanks for your time.

**Comment by piggz** [comment]
you can clear spurious entries by deleting files from /var/lib/bluetooth i think

**Comment by Jojonintendo** [comment]
This definitely did the trick. I have been searching all over the device to find the bluetooth entries, and mine was there. After that, everything just worked perfectly fine! Thank you very much for your time and help.
