### ISSUE TITLE
Can't send latin fw file to Amazfit Bip

### ISSUE THREAD

**Issue by Jojonintendo** [piggz/harbour-amazfish#67]
I have an Amazfit Bip since a few days ago, and so far so good, except I can't send the latin fw file. I am trying to send:

- Mili_chaohu.fw.latin
- Mili_chaohu.ft.latin
- Mili_chaohu.res.latin
- Mili_dth.gps

All the files are detected correctly by Amazfish, except the fw.latin one, that is "invalid". I have tried with previous releases, and the same happens, I could flash (but have not tried) all the files except the fw. I will try to flash once I know every file is detected correctly so that I can send all of them in one go.

The log from when I try to send the fw.latin file:

```
[D] unknown:0 - is firmware operation running: 0
[D] unknown:0 - is miband operation running: 0
[D] unknown:0 - Sending file  "/home/nemo/Downloads/mail_attachments/27/37-1.3/Mili_chaohu.fw.latin"
[D] unknown:0 - Determining firmware type
[D] unknown:0 - Version: "" CRC: 43876
[D] unknown:0 - -1 "" 43876
```

I'm not sure if this is normal, to prevent a non-working firmware to be flashed.

Thanks again for your time.

**Comment by piggz** [comment]
Yes, I havnt white-listed the latin fw files.  I will look to add that in the next version, atleast for this version, I dont fancy going through all the fw versions and working out the CRCs!

**Comment by Jojonintendo** [comment]
Ok, good then. I understand it can be tedious, I could give you the CRCs if you prefer. Thanks for your time anyway!

**Comment by piggz** [comment]
What is the version number for that firmware?

**Comment by Jojonintendo** [comment]
This is the latest one: 1.1.5.16, from 3.5.9 Mi Fit apk.

**Comment by piggz** [comment]
Does the resource file get detected ok?

**Comment by Jojonintendo** [comment]
Yes, every other file, even from older apks are detected correctly. Only the fw ones are flagged as invalid.

**Comment by piggz** [comment]
Added to release 0.8.8
