### ISSUE TITLE
Update Application for libicu63

### ISSUE THREAD

**Issue by je-nix** [piggz/harbour-amazfish#72]
With SFOS 3.0.3, libicu was updated to 63.1. Amazfit is linked against libicu52, which causes its removal during the update process and prevents a reinstall afterwards.
Please update the Application to use the system provided libicu63. Thanks.

**Comment by piggz** [comment]
yes, ive known about this since the first 3.0.3, i can only do it once 3.0.3 is on OBS

**Comment by je-nix** [comment]
Thanks for the reply. Can you maybe provide a version for the new libs so I can install it manually until then?

**Comment by piggz** [comment]
no, but there are instructions on openrepos for installing on 3038

**Comment by jgibbon** [comment]
For reference, the mentioned workaround can be found here: https://openrepos.net/comment/28919#comment-28919

cheers!

**Comment by je-nix** [comment]
Reinstalling the application after having manually installed libicu52 from your repository worked. However, I'm experiencing quite heavy battery drain when Amazfish is running (it more than halves the time a full charge lasts), so I'll wait until the application is adapted to 3.0.3 and refrain from using it until then.

**Comment by je-nix** [comment]
According to the release notes [1], 3.0.3 will be release to all this thursday, on 2019-05-02. It would be great to have the new build Amazfish version as soon as possible since I'm currently experiencing quite some battery drain.

[1]: https://together.jolla.com/question/203845/release-notes-303-hossa/

**Comment by piggz** [comment]
I will update it as soon as I can, but i have to wait for the oBS server to be updated first.  I would be very surprised if using the old libicu had any kind of battery drain though.

**Comment by je-nix** [comment]
You are right, that would be odd. However, I got the impression that the battery drain is reduced when I close Amazfish (yet it's highly suspective and still far worse than before the update). I guess I'll ultimately see once the new Amazfish version is here. Thank you for taking care.

In the meantime, I found a [bug report] on TJC. Maybe the issue is related to the bluetooth stack itself.

[bug report]: https://together.jolla.com/question/204357/bugbluetooth-consumes-too-much-power/

**Comment by pj-r** [comment]
Is there some place to check the oBS server status of libcu?

**Comment by je-nix** [comment]
I see you have updated the application to be usable in SFOS 3.0.3. Thanks for that.

However, the latest version 0.9.1 won't start on my phone:

`May 22 10:44:38 Sailfish mapplauncherd[4022]: Booster: Failed to invoke: Booster: Loading invoked application failed: 'libicui18n.so.52: cannot open shared object file: No such file or directory'`
`May 22 10:44:38 Sailfish lipstick[1433]: Failed to invoke: Booster: Loading invoked application failed: 'libicui18n.so.52: cannot open shared object file: No such file or directory'`
`May 22 10:44:38 Sailfish mapplauncherd[2822]: Boosted process (pid=4022) exited with status 1`
`May 22 10:44:38 Sailfish lipstick[1433]: invoker: Invoking execution: '/usr/bin/harbour-amazfish-ui'`
`May 22 10:44:39 Sailfish booster-silica-qt5[4145]: [D] unknown:0 - Using Wayland-EGL`
`May 22 10:44:39 Sailfish mapplauncherd[4145]: SilicaBooster: Initiate asynchronous preload.`

Is 0.9 still linked against libicu52 in some way?

**Comment by je-nix** [comment]
Got the application to work by manually installing libicu52 again. So far, no more battery drain. However, Amazfish seems to currently not writing to it's kexi DB. The amount of steps are shown, but sleep and every historic values shows "0". The graphical overview simply states "no data", the same when I'm trying to manually sync data. Is there any way to completely reset the App? I already tried to uninstall it, removing /home/nemo/.local/share/harbour-amafish and installing it again. But still, I get no health data.

**Comment by piggz** [comment]
your problem is odd, becuas i dont have libicu52 installed!  i think maybe you need to uninstall libicu52, and reinstall kdb-sqlite3-driver.  if you have to downgrade it, then do that becuase i think something went odd with the rebuilt version numbers, meaning that amazfish 0.9.1 needs an older version of kexidb.  zypper should offer to downgrade where needed.

**Comment by je-nix** [comment]
Thanks for the reply. Completely removing Amazfish with dependencies and reinstalling them results in kdb-sqlite3-driver libKDb3-3 being downgraded from 3.1.0-10.1.2 to 3.1.0-1.2.1. After a reboot of the phone, I can finally start Amazfish without libicu52 being installed.

I'll test, if everything is working now and get back to you. Thanks again for the help.

**Comment by je-nix** [comment]
Unfortunately, my Amazfish is still not storing any data. I removed the package with its dependencies (kdb-sqlite3-driver libKDb3-3), deleted the /home/nemo/.cache/harbour-amazfish and /home/nemo/.local/share/harbour-amazfish folders and reinstalled everything. The folders were created again, but it seems that Amazfish is not writing data into the database (the amazfish.kexi file has the tables without data in it). When I try to manually sync the data with "Down data", it always says that there is no data to transfer. But I can see that the watch is doing HRM measures regularly.

I also did a factory reset of my Amazfit watch (Please update the pairing instructions that the Amazfish Service needs to be started for the pairing to work). Still, the same issue persists. And now I can't enable the Service in the App, probably because it was still enabled when I removed the App.

Can you point me to how the service is enabled (probably it tries to create some service file somewhere)? Do you have any idea what I can try to get the data sync to work again?

**Comment by je-nix** [comment]
The comment of D_R in [OpenRepos] suggest that I'm not the only one with this issue. Should I create a new issue for it?

[OpenRepos]: https://openrepos.net/comment/29459#comment-29459

**Comment by jgibbon** [comment]
I think I may be affected as well. A dedicated issue sounds like a good idea to me. Will you create one @je-nix?

**Comment by piggz** [comment]
yeah, feel free,i also have the issue so i know what you mean

**Comment by je-nix** [comment]
New issue created: https://github.com/piggz/harbour-amazfish/issues/77

Since the update to libicu63 was implemented, I'm closing this one.
