### ISSUE TITLE
[Device] Support for Verge

### ISSUE THREAD

**Issue by svenjacobi** [piggz/harbour-amazfish#73]
Hi there,

I'm a Sailfish user and would like to have a fitness tracker that can track indoor cycling. As far as I can see the closest as I can get between these two worlds is an Amazfit Verge + using Amazfish as app.

In other issues I read that the Amazfish-code is already prepared to support multiple devices. I'm not a developer, but could you explain how one could add a new device to the code?

I assume it is about copying some files and modifying some device specific values? Or am I thinking way too simple?

**Comment by piggz** [comment]
The GTS is supported and has an indoor cycling mode btw.
