### ISSUE TITLE
[0.9.1] No fitness data transfered / shown in graphs

### ISSUE THREAD

**Issue by je-nix** [piggz/harbour-amazfish#77]
In 0.9.1, there is no data shown in the graphs of the App, only the "No data" text. The database is empty, trying to sync data manually (via menu -> "Download Data") fails with "No data to transmit". So it seems, the transmission from the watch to the App is broken.

This issue seems to affect multiple users.

**Comment by je-nix** [comment]
Steps I already tried to solve this issue:
- Reinstall Amazfish and all dependencies
- Factory Reset of the Amazfish BIP
- Removing /home/nemo/.cache/harbour-amazfish and /home/nemo/.local/share/harbour-amazfish folders

**Comment by BonoNL** [comment]
Same here, sfos 3.0.3.10 and Amazfish version V1.1.5.16.
Installed Mi Fit 3.5.9 apk because it was the last one with the right files inside.

**Comment by je-nix** [comment]
Any news regarding this issue?

**Comment by piggz** [comment]
it is working fine for me, so im struggling to reproduce! can you reboot your phone, login as root and give the output of journalctl --since today | grep amazfish, after it has connected to the watch

**Comment by jgibbon** [comment]
Hiho, as mentioned via Telegram
> In case it doesn't matter that I've tried today I can fit in a few minutes now

Here's the log after reboot:
https://pastebin.com/2dUJ3ML5

After that, I've started the manual data fetch operations on the attached pages, here's the log for that:
https://pastebin.com/4vtzPb0X

Automatic syncing is disabled in my case.

cheers

**Comment by je-nix** [comment]
Thanks jgibbon for providing the logs, I can observe the same on my device (trying to manually syncing the data results in "No data left to fetch" in the log). 

Some observations on my end while debugging:

- The date string during the sync process: "last sync was  -3600000 QDateTime(1969-12-31 23:00:00.000 UTC Qt::TimeSpec(TimeZone) UTC)". 
- The information that gets successfully updated every minute (hearth rate, battery) produces a lot of entries in the log (I counted 163 lines for the same measurement), all of the same kind, e.g.: "Jun 14 09:56:58 Sailfish harbour-amazfishd[2756]: [D] unknown:0 - slot_informationChanged AbstractDevice::Info(INFO_STEPS) "52""

As mentioned in the other thread, the sync has stopped working with the update to 0.9. a complete reinstall of Amazfish (including dependencies) does not resolve the issue. Maybe it is that old installations are continuing working, but new ones are lacking some settings / info to do so?

**Comment by jgibbon** [comment]
> Maybe it is that old installations are continuing working, but new ones are lacking some settings / info to do so?

Hm, mine failed after updating with the old icu rpm. 
I only deleted every possible config directory after that (there was one you did not mentioned above), to check. I did uninstall before removing the directories.
I don't actually remember if I also did a factory reset of the watch. Will do that if @piggz thinks it may be useful.

Just remembered: I did however, at one point way before, flash a watch firmware containing umlaut characters. Did you do that as well, @je-nix? Perhaps that's just broken somewhere?
cheers

**Comment by piggz** [comment]
ok, thats good i think.
1) i think the latest version fixes the duplicate messages bug, make sure u have restarted service after install though!
2) dconf reset /uk/co/piggz/amazfish/device/lastactivitysyncmillis and see if that helps

**Comment by je-nix** [comment]
Thanks piggz! `dconf reset /uk/co/piggz/amazfish/device/lastactivitysyncmillis` seems to have done the trick for me. After stopping and starting the service again and executing the command my watch is now syncing again and showing data for the graphs.
I'll wait if @jgibbon can solve this issue this way as well before closing it.

**Comment by jgibbon** [comment]
> Jun 14 11:36:34 Sailfish harbour-amazfishd[3050]: [D] unknown:0 - finished fetch operation, last record was  QDateTime(2019-04-24 10:27:00.000 UTC+02:00 Qt::TimeSpec(TimeZone) UTC+02:00)

Partial success: There's actually some data for two days. Will test over the next days and reset the watch if nothing newer shows up and report back.

**Comment by je-nix** [comment]
Ok, I'll wait with closing the issue then. I did a factory reset of my watch at some point.

I was able to transfer data of the previous 20 days, so 2 days seem a bit short.

**Comment by piggz** [comment]
if if downloads data for a few days ago, it wont then go back and download older data, it will only download from the point of the last successful one

**Comment by jgibbon** [comment]
The data fetched was from more or less exactly two months ago (may actually be the time I updated) and it didn't download anything newer.
After **additionally resetting the watch**, however, new data did just start to trickle in.

So, it's all good now and from my perspective, this issue is resolved.

Thank you all & cheers

**Comment by je-nix** [comment]
Closing the issue since it seems to be resolved. It can be resolved with the following steps:

1. Run the following command as root on the shell: `dconf reset /uk/co/piggz/amazfish/device/lastactivitysyncmillis`
2. If the issue is not yet resolved, factory reset the smartwatch

Thanks for the support to everyone.

**Comment by jgibbon** [comment]
1.5 You may try to repeatedly refresh data chunks manually. Ideally, all entries should be fetched as soon as it shows "No Data" again. Have an eye on the date in the notifications to be able check where data appears.

**Comment by jsikio** [comment]
@piggz I faced this problem that I didn't get any data by "Download Data". Always says "No data to transfer". I found that database is problem. Any hints what would be wrong:
Jul 02 18:58:14 Sailfish harbour-amazfishd[20578]: [D] unknown:0 - Starting amazfish daemon
Jul 02 18:58:14 Sailfish harbour-amazfishd[20578]: [D] unknown:0 - BluezAdapter::BluezAdapter
Jul 02 18:58:14 Sailfish harbour-amazfishd[20578]: [D] unknown:0 - amazfish-daemon: succesfully registered to dbus sessionBus
Jul 02 18:58:14 Sailfish harbour-amazfishd[20578]: [D] unknown:0 - Registered notifications listener for device
Jul 02 18:58:14 Sailfish harbour-amazfishd[20578]: [D] unknown:0 - DeviceFactory::createDevice: requested device of type: "Amazfit Bip Watch"
Jul 02 18:58:14 Sailfish harbour-amazfishd[20578]: [D] unknown:0 - BluezAdapter::setAdapterPath: "/org/bluez/hci0"
Jul 02 18:58:14 Sailfish harbour-amazfishd[20578]: [D] unknown:0 - DRIVERS:  ("org.kde.kdb.sqlite")
Jul 02 18:58:14 Sailfish harbour-amazfishd[20578]: [D] unknown:0 - Database is:  "/home/nemo/.local/share/harbour-amazfish/harbour-amazfish/amazfish.kexi"
Jul 02 18:58:14 Sailfish harbour-amazfishd[20578]: [D] unknown:0 - KDbConnection object created.
Jul 02 18:58:14 Sailfish harbour-amazfishd[20578]: [D] unknown:0 - KDbConnection::connect() OK.
Jul 02 18:58:14 Sailfish harbour-amazfishd[20578]: [D] unknown:0 - KDbResult: CODE=65535 MESSAGE="Tietokannan ”/home/nemo/.local/share/harbour-amazfish/harbour-amazfish/amazfish.kexi” avaaminen epäonnistui." SERVER_ERROR_CODE=0 SERVER_MESSAGE="ICU error: ucol_open(): U_FILE_ACCESS_ERROR"
Jul 02 18:58:14 Sailfish harbour-amazfishd[20578]: [W] unknown:0 - "Query failed: ICU error: ucol_open(): U_FILE_ACCESS_ERROR Unable to fetch row\nSELECT icu_load_collation('fi_FI', 'localeCollation')"

**Comment by vigejolla** [comment]
I also ran into this issue. It happened after a firmware update. factory reset (which btw did not restore the original firmware) helped.
