### ISSUE TITLE
All graphs but Analysis behave weirdly

### ISSUE THREAD

**Issue by null-von-sushi** [piggz/harbour-amazfish#81]
## Individual pages show bogus information

- Steps: Looking at future dates shows graphs/stats despite the fact [the day hasn't even occurred yet]. [E.g. 805 steps for 19th June](https://user-images.githubusercontent.com/13616397/59510864-b8f39100-8eac-11e9-9856-5bebf167a15b.png).

- Sleep: Shows the same graph for [future days as today](https://user-images.githubusercontent.com/13616397/59510720-57332700-8eac-11e9-8754-0e6bfb6483a2.png). E.g. 7.57 hours until the 22rd June,  6.97 hours for the 23rd and 'No data' after that.

- Analysis : Works perfectly 

- Sports activities : Untested as of now.

[Screen recording of everything](https://github.com/piggz/harbour-amazfish/files/3290735/untitled.zip)

[amazfish.kexi](https://github.com/piggz/harbour-amazfish/files/3290740/amazfish.zip)

**Comment by piggz** [comment]
Ah, the large indicators always show the current days stats, i could make that more obvious.

**Comment by piggz** [comment]
I now fixed the display of X axis labels in the graphs
