### ISSUE TITLE
After 0.9.1 no heart rate to Laufhelden

### ISSUE THREAD

**Issue by jsikio** [piggz/harbour-amazfish#82]
I noticed that after update to 0.9.1 I can't get heart rate to Laufhelden application (https://openrepos.net/content/jdrescher/laufhelden).

Error in log (journalctl | grep lauf):
Jun 30 19:30:42 Sailfish [5271]: [W] unknown:95 - file:///usr/share/harbour-laufhelden/qml/pages/RecordPage.qml:95:5: QML DBusInterface: QDBusError("org.freedesktop.DBus.Error.UnknownInterface", "No such interface 'org.sailfishos.heartrate' at object path '/'")

If need some more info, please ask.

I use Laufhelden 1.1.3-1, Amazfish 0.9.2-1, and Amazfit Bip fw 1.5.16

**Comment by piggz** [comment]
Thanks for the report, ill look into it

**Comment by piggz** [comment]
Fix will be in next release
