### ISSUE TITLE
Database not initialized correctly

### ISSUE THREAD

**Issue by jsikio** [piggz/harbour-amazfish#83]
Hi,
I have some problem with data fetch, as I mentioned here: https://github.com/piggz/harbour-amazfish/issues/77#issuecomment-507742690

I did some research, and seams that database is not initialized correctly and UI and daemon both do some initialization? And seems that daemon can't connect to database.

I removed /home/nemo/.local/share/harbour-amazfish/harbour-amazfish/amazfish.kexi, then start UI:
Jul 13 08:52:21 Sailfish i[3388]: [D] unknown:0 - Database is:  "/home/nemo/.local/share/harbour-amazfish/harbour-amazfish/amazfish.kexi"
Jul 13 08:52:22 Sailfish i[3388]: [D] unknown:0 - DB "/home/nemo/.local/share/harbour-amazfish/harbour-amazfish/amazfish.kexi" created
Jul 13 08:52:23 Sailfish lipstick[1843]: [D] onCompleted:267 - coverActionIndicators created harbour-amazfish-ui.desktop

Checking database:
$ sqlite3 /home/nemo/.local/share/harbour-amazfish/harbour-amazfish/amazfish.kexi
SQLite version 3.13.0 2016-05-18 10:57:30
Enter ".help" for usage hints.
sqlite> .tables
kexi__db          kexi__fields      kexi__objectdata  kexi__objects  
sqlite>

After that, I started service:
Jul 13 08:58:08 Sailfish harbour-amazfishd[5540]: [D] unknown:0 - Starting amazfish daemon
Jul 13 08:58:08 Sailfish harbour-amazfishd[5540]: [D] unknown:0 - BluezAdapter::BluezAdapter
Jul 13 08:58:08 Sailfish harbour-amazfishd[5540]: [D] unknown:0 - amazfish-daemon: succesfully registered to dbus sessionBus
Jul 13 08:58:08 Sailfish harbour-amazfishd[5540]: [D] unknown:0 - Registered notifications listener for device
Jul 13 08:58:08 Sailfish harbour-amazfishd[5540]: [D] unknown:0 - DeviceFactory::createDevice: requested device of type: "Amazfit Bip Watch"
Jul 13 08:58:08 Sailfish harbour-amazfishd[5540]: [D] unknown:0 - BluezAdapter::setAdapterPath: "/org/bluez/hci0"
Jul 13 08:58:08 Sailfish harbour-amazfishd[5540]: [D] unknown:0 - DRIVERS:  ("org.kde.kdb.sqlite")
Jul 13 08:58:08 Sailfish harbour-amazfishd[5540]: [D] unknown:0 - Database is:  "/home/nemo/.local/share/harbour-amazfish/harbour-amazfish/amazfish.kexi"
Jul 13 08:58:08 Sailfish harbour-amazfishd[5540]: [D] unknown:0 - KDbConnection object created.
Jul 13 08:58:08 Sailfish harbour-amazfishd[5540]: [D] unknown:0 - KDbConnection::connect() OK.
Jul 13 08:58:08 Sailfish harbour-amazfishd[5540]: [D] unknown:0 - KDbResult: CODE=65535 MESSAGE="Tietokannan ”/home/nemo/.local/share/harbour-amazfish/harbour-amazfish/amazfish.kexi” avaaminen epäonnistui." SERVER_ERROR_CODE=0 SERVER_MESSAGE="ICU error: ucol_open(): U_FILE_ACCESS_ERROR"
Jul 13 08:58:08 Sailfish harbour-amazfishd[5540]: [W] unknown:0 - "Query failed: ICU error: ucol_open(): U_FILE_ACCESS_ERROR Unable to fetch row\nSELECT icu_load_collation('fi_FI', 'localeCollation')"
Jul 13 08:58:08 Sailfish harbour-amazfishd[5540]: [W] unknown:0 - "Failed to configure collation for locale fi_FI:  "
Jul 13 08:58:08 Sailfish harbour-amazfishd[5540]: [D] unknown:0 - VoiceCallsChanged
Jul 13 08:58:08 Sailfish harbour-amazfishd[5540]: [D] unknown:0 - ActiveVoiceCallChanged
Jul 13 08:58:08 Sailfish harbour-amazfishd[5540]: [D] unknown:0 - DeviceInterface::connectToDevice: "/org/bluez/hci0/dev_DF_89_DE_C9_89_C9"
Jul 13 08:58:08 Sailfish harbour-amazfishd[5540]: [D] unknown:0 - QBLEDevice::setDevicePath
Jul 13 08:58:08 Sailfish harbour-amazfishd[5540]: [D] unknown:0 - true
Jul 13 08:58:08 Sailfish harbour-amazfishd[5540]: [D] unknown:0 - AbstractDevice::connectToDevice
Jul 13 08:58:08 Sailfish harbour-amazfishd[5540]: [D] unknown:0 - QBLEDevice::disconnectFromDevice
Jul 13 08:58:08 Sailfish harbour-amazfishd[5540]: [D] unknown:0 - DeviceInterface::onConnectionStateChanged "connecting"
Jul 13 08:58:08 Sailfish harbour-amazfishd[5540]: [D] unknown:0 - QBLEDevice::connectToDevice
Jul 13 08:58:09 Sailfish harbour-amazfishd[5540]: [D] unknown:0 - BipDevice::onPropertiesChanged: "org.bluez.Device1" QMap(("Connected", QVariant(bool, true))) ()
Jul 13 08:58:09 Sailfish harbour-amazfishd[5540]: [D] unknown:0 - DeviceInterface::onConnectionStateChanged "connected"

And if I tried to fetch data, I got DB error:
ul 13 09:11:09 Sailfish harbour-amazfishd[5540]: [D] unknown:0 - ...got metadata
Jul 13 09:11:09 Sailfish harbour-amazfishd[5540]: [D] unknown:0 - Finished sending data
Jul 13 09:11:09 Sailfish harbour-amazfishd[5540]: [D] unknown:0 - Database not connected

If I have UI running and remove database file and after that start service:
Jul 13 09:28:00 Sailfish harbour-amazfishd[7580]: [D] unknown:0 - DRIVERS:  ("org.kde.kdb.sqlite")
Jul 13 09:28:00 Sailfish harbour-amazfishd[7580]: [D] unknown:0 - Database is:  "/home/nemo/.local/share/harbour-amazfish/harbour-amazfish/amazfish.kexi"
Jul 13 09:28:00 Sailfish harbour-amazfishd[7580]: [D] unknown:0 - KDbConnection object created.
Jul 13 09:28:00 Sailfish harbour-amazfishd[7580]: [D] unknown:0 - KDbConnection::connect() OK.
Jul 13 09:28:00 Sailfish harbour-amazfishd[7580]: [D] unknown:0 - KDbResult: CODE=65535 MESSAGE="Virhe luotaessa tietokantaa ”/home/nemo/.local/share/harbour-amazfish/harbour-amazfish/amazfish.kexi” palvelimelle." SERVER_ERROR_CODE=0 SERVER_MESSAGE="ICU error: ucol_open(): U_FILE_ACCESS_ERROR"
Jul 13 09:28:00 Sailfish harbour-amazfishd[7580]: [W] unknown:0 - "Query failed: ICU error: ucol_open(): U_FILE_ACCESS_ERROR Unable to fetch row\nSELECT icu_load_collation('fi_FI', 'localeCollation')"
Jul 13 09:28:00 Sailfish harbour-amazfishd[7580]: [W] unknown:0 - "Failed to configure collation for locale fi_FI:  "

and /home/nemo/.local/share/harbour-amazfish/harbour-amazfish/amazfish.kexi is created but empty:
$ sqlite3 /home/nemo/.local/share/harbour-amazfish/harbour-amazfish/amazfish.kexi
SQLite version 3.13.0 2016-05-18 10:57:30
Enter ".help" for usage hints.
sqlite> .tables
sqlite> 

kdb-sqllite3-driver version:
[root@Sailfish nemo]# pkcon get-packages|grep sql
Installed    kdb-sqlite3-driver-3.1.0-10.1.2.jolla.armv7hl (installed)
Available    kdb-sqlite3-driver-3.1.0-1.2.1.jolla.armv7hl (openrepos-piggz)

And used in Xperia X, Sailfish OS 3.0.3.10 (Hossa)

**Comment by piggz** [comment]
Thanks for the detailed report...
Could you try
Close the UI
Stop the service
Delete/move the database
Start the service
Start the UI

to see if that helps, thanks

**Comment by jsikio** [comment]
Jul 13 13:57:24 Sailfish harbour-amazfishd[9811]: [D] unknown:0 - Starting amazfish daemon
Jul 13 13:57:24 Sailfish harbour-amazfishd[9811]: [D] unknown:0 - BluezAdapter::BluezAdapter
Jul 13 13:57:26 Sailfish harbour-amazfishd[9811]: [D] unknown:0 - amazfish-daemon: succesfully registered to dbus sessionBus
Jul 13 13:57:26 Sailfish harbour-amazfishd[9811]: [D] unknown:0 - Registered notifications listener for device
Jul 13 13:57:26 Sailfish harbour-amazfishd[9811]: [D] unknown:0 - DeviceFactory::createDevice: requested device of type: "Amazfit Bip Watch"
Jul 13 13:57:27 Sailfish harbour-amazfishd[9811]: [D] unknown:0 - BluezAdapter::setAdapterPath: "/org/bluez/hci0"
Jul 13 13:57:27 Sailfish harbour-amazfishd[9811]: [D] unknown:0 - DRIVERS:  ("org.kde.kdb.sqlite")
Jul 13 13:57:27 Sailfish harbour-amazfishd[9811]: [D] unknown:0 - Database is:  "/home/nemo/.local/share/harbour-amazfish/harbour-amazfish/amazfish.kexi"
Jul 13 13:57:27 Sailfish harbour-amazfishd[9811]: [D] unknown:0 - KDbConnection object created.
Jul 13 13:57:27 Sailfish harbour-amazfishd[9811]: [D] unknown:0 - KDbConnection::connect() OK.
Jul 13 13:57:27 Sailfish harbour-amazfishd[9811]: [D] unknown:0 - KDbResult: CODE=65535 MESSAGE="Virhe luotaessa tietokantaa ”/home/nemo/.local/share/harbour-amazfish/harbour-amazfish/amazfish.kexi” palvelimelle." SERVER_ERROR_CODE=0 SERVER_MESSAGE="ICU error: ucol_open(): U_FILE_ACCESS_ERROR"
Jul 13 13:57:27 Sailfish harbour-amazfishd[9811]: [W] unknown:0 - "Query failed: ICU error: ucol_open(): U_FILE_ACCESS_ERROR Unable to fetch row\nSELECT icu_load_collation('fi_FI', 'localeCollation')"
Jul 13 13:57:27 Sailfish harbour-amazfishd[9811]: [W] unknown:0 - "Failed to configure collation for locale fi_FI:  "
Jul 13 13:57:27 Sailfish harbour-amazfishd[9811]: [D] unknown:0 - VoiceCallsChanged
Jul 13 13:57:27 Sailfish harbour-amazfishd[9811]: [D] unknown:0 - ActiveVoiceCallChanged
Jul 13 13:57:27 Sailfish harbour-amazfishd[9811]: [D] unknown:0 - DeviceInterface::connectToDevice: "/org/bluez/hci0/dev_DF_89_DE_C9_89_C9"
Jul 13 13:57:27 Sailfish harbour-amazfishd[9811]: [D] unknown:0 - QBLEDevice::setDevicePath
Jul 13 13:57:27 Sailfish harbour-amazfishd[9811]: [D] unknown:0 - true
Jul 13 13:57:27 Sailfish harbour-amazfishd[9811]: [D] unknown:0 - AbstractDevice::connectToDevice
Jul 13 13:57:27 Sailfish harbour-amazfishd[9811]: [D] unknown:0 - QBLEDevice::disconnectFromDevice
Jul 13 13:57:27 Sailfish harbour-amazfishd[9811]: [D] unknown:0 - DeviceInterface::onConnectionStateChanged "connecting"
Jul 13 13:57:27 Sailfish harbour-amazfishd[9811]: [D] unknown:0 - QBLEDevice::connectToDevice

$ ls /home/nemo/.local/share/harbour-amazfish/harbour-amazfish/amazfish.kexi -al
-rw-r--r-- 1 nemo nemo 0 Jul 13 13:57 /home/nemo/.local/share/harbour-amazfish/harbour-amazfish/amazfish.kexi

**Comment by piggz** [comment]
ok, can you show
rpm -qi libicu
and
ls -lh /home/nemo/.local/share/harbour-amazfish/harbour-amazfish/

**Comment by jsikio** [comment]
# rpm -qi libicu
Name        : libicu
Version     : 63.1+git5
Release     : 1.1.6.jolla
Architecture: armv7hl
Install Date: Wed Apr 24 20:59:50 2019
Group       : System Environment/Libraries
Size        : 30489936
License     : MIT and UCD and Public Domain
Signature   : DSA/SHA1, Thu Mar 28 04:52:11 2019, Key ID 68ebdd7df2633ee0
Source RPM  : icu-63.1+git5-1.1.6.jolla.src.rpm
Build Date  : Thu Mar 28 04:51:35 2019
Build Host  : phost6
Relocations : (not relocatable)
Vendor      : meego
URL         : http://www.icu-project.org/
Summary     : International Components for Unicode - libraries
Description :
The International Components for Unicode (ICU) libraries provide
robust and full-featured Unicode services on a wide variety of
platforms. ICU supports the most current version of the Unicode
standard, and they provide support for supplementary Unicode
characters (needed for GB 18030 repertoire support).
As computing environments become more heterogeneous, software
portability becomes more important. ICU lets you produce the same
results across all the various platforms you support, without
sacrificing performance. It offers great flexibility to extend and
customize the supplied services.

$ ls -lh /home/nemo/.local/share/harbour-amazfish/harbour-amazfish/
total 0
-rw-r--r-- 1 nemo nemo 0 Jul 13 13:57 amazfish.kexi

**Comment by jsikio** [comment]
libicu was the right key to problem! pkcon get-packages|grep libicu show that also 
libicu52-52.1+git6-1.4.1.jolla.armv7hl (openrepos-piggz) was installed.
I removed that package, and now it works!

Thanks for help!
