### ISSUE TITLE
show missed notifications after reconnect

### ISSUE THREAD

**Issue by bonanza123** [piggz/harbour-amazfish#88]
It would be nice if the following case would be handled:
1) BT connection gets lost
2) e.g. a mail arrives
3) BT connection reestablished
4) "missed" mail from above triggers a notification on watch (only for those notifications that haven't been cleared on the phone meanwhile)

**Comment by piggz** [comment]
Sure ... i thought i implemented it, but there as cases it doesnt buffer the notifications, i'll get it fixed.

**Comment by piggz** [comment]
I think this is now fixed and will be released soon.
