### ISSUE TITLE
[feature request] Calendar reminders as notification

### ISSUE THREAD

**Issue by pj-r** [piggz/harbour-amazfish#92]
Would it be possible to get calendar reminders as notification?

**Comment by piggz** [comment]
I have now implemented calendar reminders on the GTS watch which supports an "Event Reminders" function.  What device is this request for, the Bip?

**Comment by pj-r** [comment]
Bip is what I'm currently using.

**Comment by piggz** [comment]
Closing as Bip does not have this feature and it is implemented on the GTS
