### ISSUE TITLE
Number of steps reported in Amazfish mulitplied by 10 compared with GTS

### ISSUE THREAD

**Issue by ncartron** [piggz/harbour-amazfish#96]
Using Amazfish GTS.
The GTS reports e.g. 574 steps, and Amazfish reports 5740 steps.
When sync is done, the initial number displayed is correct, but when swiping right (to go to e.g. Sleep screen) then left  (back to steps), then the number is multiplied by 10.

**Comment by piggz** [comment]
Fix committed, will be in next release.
